### ISSUE TITLE
New Riot Tournament Version

### ISSUE THREAD

**Issue by CoreyTrombley** [meraki-analytics/cassiopeia#101]
Riot has added a new tournament api to version 3. Tournament version one is still currently in place.

Also in addition to that, will this package ever support the tournament-stub endpoints?
<img width="1359" alt="screenshot 2017-04-23 14 15 36" src="https://cloud.githubusercontent.com/assets/2028391/25316142/5a26cb32-282f-11e7-9904-c5bbfa91dcfd.png">

**Comment by jjmaldonis** [comment]
We're working on adding all the new v3 endpoints, but it's going to be a bit until that's complete. The depreciation period hasn't started for the "old" endpoints, and in fact Riot hasn't even decided when it's going to start. So the "old" endpoints will likely be supported for another 3-6 months.  (Also, Riot still changes the "new" v3 endpoints sometimes, so we're waiting for them to tell us they are happy with them before we put the details on the final implementation.)

We will certainly add the new tournament-stub endpoints too when we get there. We are actually working hard on this stuff as I write this, so depending on how well things go you might see updates in the coming couple weeks. Keep an eye out here and on the forums if you want to know when things are finished!

**Comment by CoreyTrombley** [comment]
@jjmaldonis Awesome Thanks for the quick reply. Also if you need any help let me know. I don't know what is in development, I don't want to rewrite work already being done.

**Comment by CoreyTrombley** [comment]
Just a note: *v1 has stub endpoints.*

**Comment by 10se1ucgo** [comment]
that was rather quick https://discussion.developer.riotgames.com/articles/1053/v1v2-90-day-deprecation-period-has-begun.html

**Comment by jjmaldonis** [comment]
Yes it was. So we have three months to get things finished. Hopefully that won't be a problem, they are moving along pretty well.

@CoreyTrombley I read your PR but haven't thought about it significantly yet. I'd need to go back and review how we set the URL endpoint. I'm hesitant to accept it if it's a hotfix, but I'm glad it's there as a PR for others to find at least. I certainly won't close it, and if I get some time I'll dig into it. I hope that's okay.

**Comment by CoreyTrombley** [comment]
@10se1ucgo Thanks for the link. I totally missed it.

@jjmaldonis Yeah totally fine. I won't really need it much longer I hope, but still good to have. I do agree with not merging it until further planning has been done in regards to setting the URLs. I would be more than happy to assist in any way I can to help get this updated before the deprecation period ends, just let me know.

**Comment by jjmaldonis** [comment]
Thanks, will do. If the depreciation period is getting close and we haven't released the new version of Cass by then with these new endpoints, feel free to let me know. But hopefully doing all the tournament endpoints will be no big deal.

**Comment by jjmaldonis** [comment]
We decided we aren't going to support the tournament API for now.
