### ISSUE TITLE
When running "parse_match_information" example as is python gives TypeError

### ISSUE THREAD

**Issue by KSandris** [meraki-analytics/cassiopeia#110]
First of all, thank you guys so much for this, as a newcomer to all api thing and python in general your documentation is super understandable. So i tried to implement this, but even when running example itself i get the following error. 

_Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\dyrus.py", line 39, in main
    champion = match.participants["Dyrus"].champion
TypeError: list indices must be integers or slices, not str_

**Comment by fculpo** [comment]
see #86 
Example is indeed broken
