### ISSUE TITLE
Documentation is broken

### ISSUE THREAD

**Issue by quvide** [meraki-analytics/cassiopeia#112]
There's many instances but [this](http://cassiopeia.readthedocs.io/en/latest/cassiopeia/type/core/index.html#cassiopeia.type.core.summoner.Summoner.ranked_stats) is the one I spotted first. The ones below it are broken too.

Update: It's actually the docstrings that are broken. The same example: https://github.com/meraki-analytics/cassiopeia/blob/3595a27cd281d23a2c4aae59acf1a2ea799799ae/cassiopeia/type/core/summoner.py#L268

**Comment by jjmaldonis** [comment]
Yeah... I'm sorry... There are a ton of broken docstrings... We will fix it in the next version (a month-ish?).

**Comment by jjmaldonis** [comment]
Closing old issues because many things have changed with the Cass rewrite.
