### ISSUE TITLE
Some item stats are counted twice

### ISSUE THREAD

**Issue by 10se1ucgo** [meraki-analytics/cassiopeia#113]
For example, ItemStats for Doran's Blade returns 0.06, when it should be 0.03. From my understanding, I assume this is because 3% is scraped from the item description, and 3% is also returned from the API (`'PercentLifeStealMod': 0.03`) which are then added together

```python
>>> x = next(x for x in riotapi.get_items() if x.name == "Doran's Blade")
>>> x.stats.life_steal
0.06
```

I'm assuming this is only a problem on items that offer stuff as a non-passive stat.

**Comment by jjmaldonis** [comment]
Thanks, that makes sense. We'll try to fix it in this next version of Cass (a couple weeks?). If you want a fix sooner than that, feel free to submit a PR!

**Comment by jjmaldonis** [comment]
Closing old issues because many things have changed with the Cass rewrite.
