### ISSUE TITLE
ArgumentError:  Recommended column 'champion' conflicting with relationship property.

### ISSUE THREAD

**Issue by H3yfinn** [meraki-analytics/cassiopeia#115]
Hi all,
I've been using the automapping from SqlAlchemy and came across this error:

`ArgumentError: WARNING: when configuring property 'champion' on Mapper|Recommended|Recommended, column 'champion' conflicts with property '<RelationshipProperty at 0x7f639bc56c88; champion>'. To resolve this, map the column to the class under a different name in the 'properties' dictionary.  Or, to remove all awareness of the column entirely (including its availability as a foreign key), use the 'include_properties' or 'exclude_properties' mapper arguments to control specifically which table columns get mapped.`

Here's my code:
```
`from sqlalchemy.orm import sessionmaker
from sqlalchemy.engine import create_engine

engine = create_engine("postgresql://", echo=False)

from sqlalchemy import MetaData, Table, Column, ForeignKey
from sqlalchemy.ext.automap import automap_base
# produce our own MetaData object
metadata = MetaData()

# we can reflect it ourselves from a database, using options
# such as 'only' to limit what tables we look at...
metadata.reflect(engine)

# we can then produce a set of mappings from this MetaData.
Base = automap_base(metadata=metadata)

# calling prepare() just sets up mapped classes and relationships.
Base.prepare()

# mapped classes are ready
player, match_detail, participant, participant_stats= Base.classes.MatchPlayer, Base.classes.MatchDetail, \
Base.classes.MatchParticipant, Base.classes.MatchParticipantStats

session = sessionmaker(bind=engine)
session = session()

`
```

Wondering if anyone has a quick fix for this. I've tried a few things but I guess my SqlAlchemy knowledge is a bit brief.

**Comment by jjmaldonis** [comment]
Closing old issues because many things have changed with the Cass rewrite.
