### ISSUE TITLE
Sensible data should be loaded from env variable

### ISSUE THREAD

**Issue by fculpo** [meraki-analytics/cassiopeia#117]
v3 related: 

Settings like API_KEY could be loaded from environment variable, to allow versioning of default.ini and its usage in forks.

Not doing this forces to launch cass with another .ini file, that cannot be versionned for security reasons.

**Comment by fculpo** [comment]
Note: I could not create nor assign any label to the issue

**Comment by jjmaldonis** [comment]
Already implemented, just not documented!

https://github.com/meraki-analytics/cassiopeia/blob/v3-development/cassiopeia/configuration/settings.py#L66
