### ISSUE TITLE
Cassiopeia + SQLAlchemy 

### ISSUE THREAD

**Issue by L3murCatta** [meraki-analytics/cassiopeia#118]
Hello everyone.

I was trying to use this library to run the match_collection example (https://github.com/meraki-analytics/cassiopeia/blob/master/examples/match_collection.py). However, when the database is used for storage, I get the following error at the `unpulled_summoners = deque(entry.summoner for entry in riotapi.get_master())` line.

`sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: 'latin-1' codec can't encode character '\u015b' in position 3: ordinal not in range(256)`

The database was created with CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, so one would expect no such problems with codecs. For some time I thought that SQLAlchemy is somehow stuck at the point where my database hadn't yet had unicode support, so ended up dropping and recreating the database. The problem persisted, and I'm kinda lost.

Have anyone else encountered this problem and how do you solve it? My OS is Windows 10, if that matters.

**Comment by ShabdizG** [comment]
*Bump* 
Have the same problem for quite some time!

**Comment by jjmaldonis** [comment]
Closing old issues because many things have changed with the Cass rewrite.
