### ISSUE TITLE
how to request match history by date? 

### ISSUE THREAD

**Issue by pquadri** [meraki-analytics/cassiopeia#147]
I've tried 
```
begin_data = datetime.datetime(2017, 9, 1, 0, 0)
end_data = datetime.datetime(2017, 10, 17, 0, 0)
match_history = MatchHistory(summoner=summoner,begin_index = 0, end_index = 100, begin_time= begin_data, end_time = end_data)
```

to get the last 100 games or the ones played in the last period of time, but the date condition just gets ignored and if i remove the index condition i get all my games all the way from season 3

**Comment by jjmaldonis** [comment]
Hmm the date condition isn't working quite right right now. Until we get it fixed, you can do something like this:

    match_history = MatchHistory(summoner=summoner,begin_index = 0, end_index = 100, begin_time= begin_data, end_time = end_data)
    end = None
    for i, match in enumerate(match in match_history):
        if match.creation < begin_data:
            end = index - 1
            break
    match_history = match_history[:end]

By not iterating over the whole match history, you won't pull all the data.

**Comment by jjmaldonis** [comment]
Okay, this should be fixed now. The below works for me:

    match_history = cass.get_match_history(summoner, region=region, seasons={Season.season_7}, queues={Queue.ranked_solo_queue}, begin_time=datetime.datetime.fromtimestamp(1508290306), end_time=datetime.datetime.fromtimestamp(1508463106))


Commit hash: cb24189b22e184453722b0cf1b4b78f12cbbce3c

I'll close this, but feel free to reopen it if you are still seeing issues.
