### ISSUE TITLE
get_match_history is with problem

### ISSUE THREAD

**Issue by MarcusMann** [meraki-analytics/cassiopeia#155]
every time I make a request to get_match_history returns this:

matches = cassiopeia.get_match_history('barril')

TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

thanks

**Comment by jjmaldonis** [comment]
Thanks, could you try updating Cass one more time and seeing if you still have the issue?

**Comment by MarcusMann** [comment]
Thanks for reply @jjmaldonis .

This attempt causes an error.

```
summoner = cassiopeia.get_summoner (name = "go")
match = cassiopeia.get_match_history (summoner = summoner)

```
**PS - my package is all up to date.**
