### ISSUE TITLE
Converting Cassiopeia object into JSON

### ISSUE THREAD

**Issue by NullCodex** [meraki-analytics/cassiopeia#157]
Hi, apologies ahead of time if this is not the best place to ask this question. But I'm having issues converting the Cassiopeia python objects into JSON so that I can dump the data somewhere.

Is there an easy option that allows me for instance to store the Match data as a JSON format?

thanks!

**Comment by jjmaldonis** [comment]
Right now it's kinda a pain to do that. One thing you can do is manually extract out the data you want into a dictionary, and then dump that to json.

It's on our todo list to add this feature, but we haven't gotten to it yet.

**Comment by tyuo9980** [comment]
@jjmaldonis It is probably much easier to add an option to return the raw JSON from RiotAPI.

**Comment by jjmaldonis** [comment]
I just pushed a new method for serializing objects to json. It's called `to_json` and takes the same kwargs as the `json.dumps` command. For example, `match.to_json(indent=2)`.

I haven't tested it too much but it should work in most cases.
