### ISSUE TITLE
API calls take a long time (10 seconds) when using cassiopeia

### ISSUE THREAD

**Issue by NiliusJulius** [meraki-analytics/cassiopeia#158]
Every call that has to be made to the API takes about 10 seconds to complete.
I've narrowed it down to cassiopeia/cassiopeia/datastores/common.py. The curl.perform() inside the HTTPClient class is what is taking up all of the time.

Is this normal or is there any reason this happens?

**Comment by jjmaldonis** [comment]
It's normal if you are being rate limited. Also some calls take longer than others because the data being returned is MBs of data. We chose curl because it's faster than the other options. I've never seen 10 second request times on my end.

**Comment by martinzlocha** [comment]
Having the same issue with the following code:

```
    summoner = summoners.pop()
    seen.append(summoner.id)

    match_history = summoner.match_history

    print(datetime.now())
    for match in match_history:
        for p in match.participants:
            if p.summoner.id not in seen:
                summoners.append(p.summoner)
                print(datetime.now())
```

The printed results are:

```
2017-11-12 21:22:28.761785
Making call: https://na1.api.riotgames.com/lol/match/v3/matchlists/by-account/32746443?beginIndex=0&endIndex=100
Making call: https://ddragon.leagueoflegends.com/realms/na.json
Making call: https://na1.api.riotgames.com/lol/match/v3/matches/2640166616
2017-11-12 21:23:50.157810
```

Definitely not an issue with my internet connection.

**Comment by jjmaldonis** [comment]
That bit of code runs in less than 5 seconds for me. I don't know what to tell you.

**Comment by NiliusJulius** [comment]
My problem was definetly pycurl related. Manually doing pycurl calls also took about 10 seconds. However it seems to have fixed itself after a full pc reboot.

**Comment by martinzlocha** [comment]
Umm fixed after completely uninstalling all requirements and reinstalling. Thanks @NiliusJulius @jjmaldonis
