### ISSUE TITLE
Option to return raw JSON instead of Cassiopeia obj

### ISSUE THREAD

**Issue by tyuo9980** [meraki-analytics/cassiopeia#163]
In many cases the frontend of a web app would like raw json from riotapi to work with. Currently specific fields must be cherrypicked and re-serialized from the backend. Cassiopeia should provide the option to return raw json without serializing the object.

**Comment by jjmaldonis** [comment]
We don't have any plans to provide raw, unserialized json to frontends right now. That ~ defeats the purpose of Cass, which is meant as a nice interface for interacting with the data it handles. If a user doesn't want to interact with the data in python, and instead just wants to pass unserialized data along to their frontend, there are better ways to do that and Cass is overkill.

In the future we will release a separate library called Kernel that is meant to be a caching/databasing layer for a backend, which lets data pass to/from it. It's possible we might provide functionality like this in Kernel, but that will be a separate project.

I mentioned in issue #157 that we plan to have a method to dump an object to json, but there are some other infrastructure things that need to happen first to get things to the point where that is reasonable. If a user really just wants dictionary-like objects straight from the Riot API, they can directly call `cassiopeia.configuration.settings.pipeline.get(...)` on a `*Dto` object; but if that's all the user wants to do (which means they don't get all the nice user-interface functionality we provide), they should use a library like RiotWatcher instead.
