### ISSUE TITLE
Caching and stale data

### ISSUE THREAD

**Issue by tyuo9980** [meraki-analytics/cassiopeia#165]
I noticed that these objects are cached.
```
CurrentMatch: datetime.timedelta(hours=0.5)
FeaturedMatches: datetime.timedelta(hours=0.5)
```
The cache wouldn't know if the match was over, so if you request the currentmatch right before the match actually ends, it will end up caching it for 30min, then the player could get into another match 5 minutes afterwards, thus any subsequent calls to currentmatch would be incorrect.

As a side question: apply_settings(filename) would try to find the .json within the _configurations folder and doesnt seem to accept a path

Also this doenst work for me. I'm calling cass.apply_settings passing in a python dict
```
"Cache": {
        "CurrentMatch": datetime.timedelta(hours=0.5)
 },
```
What is the correct way of overriding the cache defaults?
```
s = cass.get_summoner(name="Kalturi")
  File "/Users/peterli/miniconda3/lib/python3.6/site-packages/cassiopeia/cassiopeia.py", line 97, in get_summoner
    return Summoner(id=id, account=account, name=name, region=region)
  File "/Users/peterli/miniconda3/lib/python3.6/site-packages/cassiopeia/core/common.py", line 46, in default_region_wrapper
    return method(self, *args, **kwargs)
  File "/Users/peterli/miniconda3/lib/python3.6/site-packages/cassiopeia/core/common.py", line 182, in __call__
    pipeline = configuration.settings.pipeline
  File "/Users/peterli/miniconda3/lib/python3.6/site-packages/cassiopeia/_configuration/settings.py", line 221, in pipeline
    verbose=0)
  File "/Users/peterli/miniconda3/lib/python3.6/site-packages/cassiopeia/_configuration/settings.py", line 31, in create_pipeline
    store = store_cls(**config)
```

**Comment by jjmaldonis** [comment]
>The cache wouldn't know if the match was over, so if you request the currentmatch right before the match actually ends, it will end up caching it for 30min, then the player could get into another match 5 minutes afterwards, thus any subsequent calls to currentmatch would be incorrect.

This idea of "requesting an object just before it changes means that it's cached after it has changed" is true of every data type, not just `CurrentMatch`. We have to make decisions about what is reasonable behavior, and have to balance reasonable caching times with incorrect/current data. As you mentioned, you can change the defaults if you don't like them, that's why we made them configurable from the settings.

You can't just pass in a partial settings dict. You need to define the entire settings, not just a small part of it.

`cass.apply_settings` doesn't take a filename, it takes a dictionary.

You can use `cass.get_default_config` to get a copy of the default config, and modify the dictionary before passing it into `cass.apply_settings`.

**Comment by tyuo9980** [comment]
Passing all the cache objects taken directly from default_expirations in cache.py gives me the same error.
```
cass.apply_settings({
  "global": {
    "default_region": None
  },

  "pipeline": {
    "Cache": {
      "ChampionStatusData": datetime.timedelta(hours=6),
      "ChampionStatusListData": datetime.timedelta(hours=6),
      "Realms": datetime.timedelta(hours=6),
      "Versions": datetime.timedelta(hours=6),
      "Champion": datetime.timedelta(days=20),
      "Rune": datetime.timedelta(days=20),
      "Item": datetime.timedelta(days=20),
      "SummonerSpell": datetime.timedelta(days=20),
      "Map": datetime.timedelta(days=20),
      "ProfileIcon": datetime.timedelta(days=20),
      "Locales": datetime.timedelta(days=20),
      "LanguageStrings": datetime.timedelta(days=20),
      "SummonerSpells": datetime.timedelta(days=20),
      "Items": datetime.timedelta(days=20),
      "Champions": datetime.timedelta(days=20),
      "Runes": datetime.timedelta(days=20),
      "Maps": datetime.timedelta(days=20),
      "ProfileIcons": datetime.timedelta(days=20),
      "ChampionMastery": datetime.timedelta(days=7),
      "ChampionMasteries": datetime.timedelta(days=7),
      "LeagueEntries": datetime.timedelta(hours=6),
      "League": datetime.timedelta(hours=6),
      "ChallengerLeague": datetime.timedelta(hours=6),
      "MasterLeague": datetime.timedelta(hours=6),
      "Match": datetime.timedelta(days=3),
      "Timeline": datetime.timedelta(days=1),
      "Summoner": datetime.timedelta(days=1),
      "ShardStatus": datetime.timedelta(hours=1),
      "CurrentMatch": -1,
      "FeaturedMatches": -1
    },

    "DDragon": {},

    "RiotAPI": {
      "api_key": "RIOT_API_KEY"
    }
  },

  "logging": {
    "print_calls": True,
    "print_riot_api_key": False,
    "default": "WARNING",
    "core": "WARNING"
  }
})
```

**Comment by jjmaldonis** [comment]
Please use `cass.get_default_config()` and modify the return value. That we you are guaranteed to get the correct settings structure. You're missing the keyword `expirations` or something like that in the `Cache`.

**Comment by tyuo9980** [comment]
There is no get_default_config defined. The only place where it i can find it is in settings.py which returns what i have with an empty cache obj
