### ISSUE TITLE
match Participant reports incorrect summoner when run more than once

### ISSUE THREAD

**Issue by r000t** [meraki-analytics/cassiopeia#169]
If a match is looked up from a summoner's match history, and participant data is retrieved, on a subsequent run with /any/ summoner from that match, the first participant returned will be some other person in the match, but it will look an awful lot like the summoner being looked up played that champion and had those stats. 

Additionally, if you iterate through all participants, on the first run, the "some other person"'s stats will never appear, and the person being looked up will appear twice. On subsequent runs, all stats will appear, but the "some other person"'s stats will be attributed to whoever is being looked up.

Disabling ghost loading will cause this to happen immediately, instead of on subsequent runs. On the latest revision, it is necessary to disable ghost loading, because ghost loading prevents accessing summoner.name for a participant. 

Test case on latest revision from Github:

```
import cassiopeia as riot

def simpleNickToChampMap(summoner):
    summoner = riot.get_summoner(name=summoner)
    history = summoner.match_history

    lastMatchID = int(history[0].id)
    for i in riot.Match(id=lastMatchID).participants:
        print(i.summoner.name, "playing", i.champion.name)

 

print("Running once...")        
simpleNickToChampMap("return3")
print("\n"*5)
print("Running again...")
simpleNickToChampMap("return3")
print("Whoever you looked up will always appear to be playing the first champion enumerated, instead of whoever is actually playing that champion.")
print("Additionally, that champion never appears in the first enumeration. It's clobbered by whoever you looked up.")
print("Now we will look up anybody else in that match. They will also be playing Veigar.")
print("\n"*5)
simpleNickToChampMap("ZAMURIJACK")
```

Example output without ghost loading (problem will occur immediately). In the first two runs, you can see me playing two champions at once. In the third run, you can see ZAMURIJACK playing two champions at once. 

ReTuRn3 playing Veigar
Kirishîma Touka playing Sona
Rocknrolking playing Varus
NVxTittyBanger playing Darius
bullpupsniper playing Elise
ZAMURIJACK playing Kha'Zix
Zenà playing Yasuo
Cry More Pls playing Draven
Not Reiko playing Morgana
ReTuRn3 playing Ekko 

ReTuRn3 playing Veigar
Kirishîma Touka playing Sona
Rocknrolking playing Varus
NVxTittyBanger playing Darius
bullpupsniper playing Elise
ZAMURIJACK playing Kha'Zix
Zenà playing Yasuo
Cry More Pls playing Draven
Not Reiko playing Morgana
ReTuRn3 playing Ekko

ZAMURIJACK playing Veigar
Kirishîma Touka playing Sona
Rocknrolking playing Varus
NVxTittyBanger playing Darius
bullpupsniper playing Elise
ZAMURIJACK playing Kha'Zix
Zenà playing Yasuo
Cry More Pls playing Draven
Not Reiko playing Morgana
ReTuRn3 playing Ekko

**Comment by jjmaldonis** [comment]
fixed with afe4e895bc08509a728863949b92db7715bc37b8
