### ISSUE TITLE
'MatchReferenceData' object has no attribute 'lane'

### ISSUE THREAD

**Issue by TheSpiritof69** [meraki-analytics/cassiopeia#186]
I have two matches in my match history that do not have the mentioned attributes and break cassiopeia working through the history. Immediate previous and following matches have lane attributes as seen below

Directly from the Riot API:

> "matches": [
{
"platformId": "EUW1",
"gameId": 1995911865,
"champion": 429,
"queue": 2,
"season": 5,
"timestamp": 1425317089406
},
{
"platformId": "EUW1",
"gameId": 1995643966,
"champion": 236,
"queue": 65,
"season": 5,
"timestamp": 1425301673317
},
{
"platformId": "EUW1",
"gameId": 1989516511,
"champion": 68,
"queue": 65,
"season": 5,
"timestamp": 1424978089703,
"role": "NONE",
"lane": "MID"
},
...

Any recommendations on how to proceed?

**Comment by jjmaldonis** [comment]
Interesting. I've never seen these fields missing. These matches are from a long time ago though.

I just pushed a fix, so if you pip-install from github (see the setup docs if you need the command), this should be fixed. I didn't have a summoner / query to easily test the fix I made, however, so if you know what call can reproduce the error you saw, that would be helpful too.

**Comment by TheSpiritof69** [comment]
Oh yea, my match history goes back  ~3000ish games to about S4..

I have no idea why these fields are missing because the queues were the same actually.
Thanks for the fix though :)
