### ISSUE TITLE
Skins request error.

### ISSUE THREAD

**Issue by edemilson** [meraki-analytics/cassiopeia#193]
Hi,
When I use skin request of champion I receive that error:

![image](https://user-images.githubusercontent.com/3835651/35528088-e5be98fc-0513-11e8-86ae-c4cad51c265d.png)

I change in file champion.py line 404 setting one forced ID and worked. I don't did the correction because I am a newbie in python.

Sorry, my bad English :)

**Comment by jjmaldonis** [comment]
No problem your english is good. Could you please post your code? I am not able to reproduce your error. Another person is having the same issue, too, so it isn't just you.
