### ISSUE TITLE
Custom games bug because of participantIdentities.

### ISSUE THREAD

**Issue by davidherasp** [meraki-analytics/cassiopeia#197]
So I recently started using Cassiopeia because I want to do data analysis of the games of a regional league and that games are custom. First thing I tried was to just export that game or a participant to a dict but since the only data at participantIdentities is this: 
`"participantIdentities":[{"participantId":1},{"participantId":2},{"participantId":3},{"participantId":4},{"participantId":5},{"participantId":6},{"participantId":7},{"participantId":8},{"participantId":9},{"participantId":10}]` 

instead of that:
`"participantIdentities":[{"participantId":1,"player":{"platformId":"EUW1","accountId":32119097,"summonerName":"quentindix","summonerId":28320728,"currentPlatformId":"EUW1","currentAccountId":32119097,"matchHistoryUri":"/v1/stats/player_history/EUW1/32119097","profileIcon":3193}},{"participantId":2,"player":{"platformId":"EUW1","accountId":201181906,"summonerName":"FANK Droptex","summonerId":42241039,"currentPlatformId":"EUW1","currentAccountId":201181906,"matchHistoryUri":"/v1/stats/player_history/EUW1/201181906","profileIcon":687}},{"participantId":3,"player":{"platformId":"EUW1","accountId":201879852,"summonerName":"QueZak is MVP","summonerId":43169552,"currentPlatformId":"EUW1","currentAccountId":201879852,"matchHistoryUri":"/v1/stats/player_history/EUW1/201879852","profileIcon":774}},{"participantId":4,"player":{"platformId":"EUW1","accountId":229155190,"summonerName":"EyXoTiiiC2","summonerId":90507752,"currentPlatformId":"EUW1","currentAccountId":229155190,"matchHistoryUri":"/v1/stats/player_history/EUW1/229155190","profileIcon":7}},{"participantId":5,"player":{"platformId":"EUW1","accountId":34843740,"summonerName":"JiBeNSip","summonerId":31042316,"currentPlatformId":"EUW1","currentAccountId":34843740,"matchHistoryUri":"/v1/stats/player_history/EUW1/34843740","profileIcon":3186}},{"participantId":6,"player":{"platformId":"EUW1","accountId":224612364,"summonerName":"DaHebadinga55","summonerId":79959911,"currentPlatformId":"EUW1","currentAccountId":224612364,"matchHistoryUri":"/v1/stats/player_history/EUW1/224612364","profileIcon":3180}},{"participantId":7,"player":{"platformId":"EUW1","accountId":27965530,"summonerName":"Pockesen","summonerId":23714141,"currentPlatformId":"EUW1","currentAccountId":27965530,"matchHistoryUri":"/v1/stats/player_history/EUW1/27965530","profileIcon":1132}},{"participantId":8,"player":{"platformId":"EUW1","accountId":21803320,"summonerName":"aPray","summonerId":19141489,"currentPlatformId":"EUW1","currentAccountId":21803320,"matchHistoryUri":"/v1/stats/player_history/EUW1/21803320","profileIcon":546}},{"participantId":9,"player":{"platformId":"EUW1","accountId":211284923,"summonerName":"Missing Q","summonerId":60077837,"currentPlatformId":"EUW1","currentAccountId":211284923,"matchHistoryUri":"/v1/stats/player_history/EUW1/211284923","profileIcon":1114}},{"participantId":10,"player":{"platformId":"EUW1","accountId":22516321,"summonerName":"Helliz","summonerId":19687130,"currentPlatformId":"EUW1","currentAccountId":22516321,"matchHistoryUri":"/v1/stats/player_history/EUW1/22516321","profileIcon":3168}}]`

it would just throw the following error:
> C:\Users\david\Anaconda3\lib\site-packages\cassiopeia\core\match.py in __call__(self, **kwargs)
    209                 for pid in kwargs["participantIdentities"]:
    210                     if participant["participantId"] == pid["participantId"]:
--> 211                         participant["player"] =  pid["player"]
    212                         break
    213             self.participants = []
**KeyError**: 'player'

I forked the repo to try to solve the bug but in the meantime, do you know if there is any simple or possible workaround to just get all the data of the custom matches without getting errors?

Thanks in advance!

**Comment by jjmaldonis** [comment]
Hmm we haven't put much effort into supporting custom games without player information because I didn't think the API even returned them.  If all you want is a dict of the data, I would actually say you might want to use Riot Watcher (another Riot API library) instead. Cass is meant more as a full-featured library with a bunch of usability-focused features, and it's more complicated because of that, so fixing this bug might take a bit.

But if all you want is dicts, then Riot Watcher might be the way to go. Either way, can you paste some example code here that is causing this error? I'll try to look into it too.

**Comment by davidherasp** [comment]
Thanks! I'll have a look at Riot Watcher then. I can understand your point and the use cases you pursue. At the end all I want is work with Pandas DataFrames and yeah, a dict is just fine :)

Pretty much everything you want to pull from the custom match data will throw the same error. Here is an example of a custom match and a call to its queue resulting in that error.

```python
import cassiopeia as cass

custom_match = cass.get_match(id=3511957748)
custom_match.queue
```

**Comment by jjmaldonis** [comment]
This might have been an easier fix than I was expecting. If you are still using Cass, could you repulling from Github (`pip install --upgrade git+https://github.com/meraki-analytics/cassiopeia.git`) and try again? I think I've got it fixed.

**Comment by davidherasp** [comment]
Awesome!! That was quick. I'll try this afternoon as soon as I get home although I already started using RiotWatcher and it's pretty much what I needed. Sorry, I forgot to tell you that the region of the game was EUW 😋

**Comment by davidherasp** [comment]
I have just tried the new version and looks like is working just fine. Thanks for taking the time!
