### ISSUE TITLE
Throw unique error on .load() object already loaded

### ISSUE THREAD

**Issue by tyuo9980** [meraki-analytics/cassiopeia#205]
It would be more meaningful if there was an error object specifically for the object already loaded case. This way I can catch it and differentiate it from other possible errors it may throw such as a riot api failure exception, etc.

**Comment by jjmaldonis** [comment]
As a user you should never see an `object already loaded` error unless there is a bug. Where are you seeing this?

**Comment by tyuo9980** [comment]
Sorry i should have been more clear. I meant to suggest the idea of throwing an error specifically for already loaded objects, or have .load() not try to reload the object if it has already been loaded.

**Comment by jjmaldonis** [comment]
Ah ok gotcha. I pushed a fix to prevent `.load()` from reloading already loaded objects, so that should just pass silently now and you shouldn't need to worry about catching this error.

**Comment by tyuo9980** [comment]
Thanks that sounds great
