### ISSUE TITLE
*Critical* - Loading match from wrong region

### ISSUE THREAD

**Issue by tyuo9980** [meraki-analytics/cassiopeia#206]
As you can see the player made a region switch to euw from eune. Because he is current in euw1, the eun1 matches will still appear in the matchlist api. When cassiopeia tries to retrieve the matches, it does not check the platform id and will grab the match for the wrong region.
```
 {
            "lane": "JUNGLE",
            "gameId": 3512444826,
            "champion": 113,
            "platformId": "EUW1",
            "timestamp": 1517335140200,
            "queue": 420,
            "role": "NONE",
            "season": 11
        },
        {
            "lane": "JUNGLE",
            "gameId": 1899106164,
            "champion": 113,
            "platformId": "EUN1",
            "timestamp": 1517323859162,
            "queue": 420,
            "role": "NONE",
            "season": 11
        },
```

**Comment by jjmaldonis** [comment]
This looks like an error on Riot parts rather than in Cass. Make sure you carefully check the data returned from Riot using the Dev Portal before making an issue. You also need to provide explicit code to reproduce the problem; the information you provide is not nearly enough to figure out what's going on, or even how you got this information.

**Comment by tyuo9980** [comment]
The json provided above is from riot api directly on their matchlist endpoint. Ill doublecheck on the forums if this is indeed intentional on their part.

ml = cass.get_match_list(s)
ml[0] calls rito api and loads match correctly. 
ml[1] calls rito api, attempts to load match but no error is thrown. 

I investigated this bug by checking riot api what matches are being returned from amtchlist. It turns out that the platforms in thr matchlist json may differ. I suspect the reason for this is from region changes. The problem is if i try to access ml[1]. Attributes will be missing

**Comment by tyuo9980** [comment]
I asked on discord and had two people confirm that this response is expected and that an account may be linked to multiple ids if they region swapped. So you may look up a summoner with ids from either region and it would return the same matchlist.

**Comment by jjmaldonis** [comment]
I tried for like half an hour to figure out what was going on by hand but couldn't figure it out. I tried to find the summoner ID you used in your original post but either couldn't find it or wasn't able to reproduce your results.

I didn't see anything on the Riot forums about this, but every summoner that I thought I knew about that switched regions didn't seem to have any matches from different regions in their match history (using the dev portal) (this was different from what I'd seen a few months ago, where I could request a summoner's match history and get matches from different regions). I even wrote a script to try to find a summoner that swapped regions but it didn't find anything after like an hour so I just cancelled it.

If you can find a summoner that swapped regions let me know.
