### ISSUE TITLE
Wierd Issue/Question with Console Output

### ISSUE THREAD

**Issue by Roxashe** [meraki-analytics/cassiopeia#209]
Hi!

Having a super wierd issue with this pypi package. Whenever I import your module, it seems to break console output. As in, it stops any and all console output in my terminal, which is super important for me to see. It only happens when I import cassiopeia and have tested this to make sure this is the only thing causing it at the moment.

**Comment by Roxashe** [comment]
Found the line that does this. We run our own Async app (A discord bot) and we use the logger in a different way. It seems to clash, disabling out output. The offending line is:
logging.basicConfig(format='%(asctime)s: %(message)s', datefmt='%Y-%m-%d %H:%M:%S', level=logging.WARNING)
Commenting this out fixes the output for us.

**Comment by jjmaldonis** [comment]
Ok good to know. We haven't spent a lot of time on the logging stuff. We'll try to get a fix for this at some point though.
