### ISSUE TITLE
Duplicate Flex 3v3 Queues

### ISSUE THREAD

**Issue by kihashi** [meraki-analytics/cassiopeia#213]
I'm running into an issue with the ranked 3v3 queues. It looks to me like the current queue and the "depreciated" queue are equal.

```
>>> cass.Queue.depreciated_ranked_flex_threes == cass.Queue.ranked_flex_threes
True
```

This causes problems with evaluation of things like, "Which queue is this league for?". For example, when looking at the league info for my summoner--

```
>>> cass.Summoner(name="Kihashi", region="NA").leagues[0].queue
<Queue.depreciated_ranked_flex_threes: 'RANKED_FLEX_TT'>
```

Since this is data for the current season, I would not expect the output to be the "depreciated" queue. I would expect it to be `Queue.ranked_flex_threes`.

Is this expected behavior or is this just a result of the enum being the same value?

(Also, I'm a little confused by the used of "depreciated" vs "deprecated").

**Comment by jjmaldonis** [comment]
You can you use the `is` operator rather than  `==` to check enums -- that's the standard syntax. Some of the queues are unintuitive due to Riot's naming scheme before they standardized queues, so that's what your'e seeing here. "depreciated" was a typo that I kept forgetting to fix. The names are updated now.

**Comment by kihashi** [comment]
@jjmaldonis The problem is that the deprecated queue (Id # 9) is being given for a current league, which should be returning the non-deprecated queue (Id # 470). 

Here's the raw response from the API:
```
> https://na1.api.riotgames.com/lol/league/v3/positions/by-summoner/47160
...
 "queueType": "RANKED_FLEX_TT"
...
```
I'm assuming that it's being converted to the enum based on that string and since the deprecated one has the same value as the non-deprecated one, it uses it first.
