### ISSUE TITLE
Option to expire cache

### ISSUE THREAD

**Issue by tyuo9980** [meraki-analytics/cassiopeia#215]
There is no option to expire the cache currently (based on my futile attempts to get datastores.Cache.expire() working), which makes cass consume quite a bit of memory when left running for a while.

Underlying issue in #216

**Comment by jjmaldonis** [comment]
I'm pretty sure the `.expire` function works correctly. Are you looking for the `clear` method instead?

**Comment by tyuo9980** [comment]
Can you provide an usage example?

**Comment by jjmaldonis** [comment]
```python
my_cache = cass.configuration.settings.pipeline._cache  # off the top of my head
my_cache.clear(Match)  # Deletes all Match data in the cache
```

The `.expire` method will only remove data if it's out-of-date, the `.clear` method will remove the data no matter what.

**Comment by tyuo9980** [comment]
'''
>>> m = cass.get_match(2726687109, region='NA')
>>> m.load()
Making call: https://na1.api.riotgames.com/lol/match/v3/matches/2726687109
<cassiopeia.core.match.Match object at 0x10c59f0f0>
>>> cass_cache.clear(cass.core.Match)
>>> m.load()
<cassiopeia.core.match.Match object at 0x10c59f0f0>
>>> 
'''

**Comment by tyuo9980** [comment]
How is clear implemented exactly? I need it to free memory but i dont think thats happening since the garbage collector isnt collecting anything

**Comment by jjmaldonis** [comment]
By default, Cass will look for an environment variable called `RIOT_API_KEY` and use that. You can override that multiple ways, check the docs for more info.

You can dig into the clear implementation starting here: https://github.com/meraki-analytics/cassiopeia/blob/master/cassiopeia/datastores/cache.py#L133
