### ISSUE TITLE
participantstats

### ISSUE THREAD

**Issue by aluckyhit** [meraki-analytics/cassiopeia#239]
So, I'm trying to work through this, form your example match.py code you have a list of p = match.participants[summoner].  So if I wanted the stats of these participants wouldn't it just be p = match.participantstats[summoner]? That doesn't run and I'm unsure of why.

Also thanks for your work so far!

**Comment by jjmaldonis** [comment]
Good question! What you want here is:

`stats = match.participants[summoner].stats`

The way to think about it is like this:  `p = match.participants[summoner]` gives me the participant in the match that corresponds to the summoner I want. Then I want the stats of that participant, so I run `stats = p.stats`. Those two lines of code can be combined into the one I wrote above: `stats = match.participants[summoner].stats`.

So first you get the participant that you care about, then you get that participant's stats.

Let me know if that didn't make sense and I will try to explain it better.

**Comment by aluckyhit** [comment]
Thanks! Couple more questions, I'm sorry I am really knew to this.  I am pulling Fakers data and stuff like the summoner spells is in Korean, so I just wanted to get the image, but it gives me class 'cassiopeia.core.staticdata.common.ImageData'>": '<cassiopeia.core.staticdata.common.ImageData object at 0x0000000015392E80.  

Furthermore for the items I am doing 
p = match.participants[summoner] 
item_list=Items(included_data=p.stats.items,region="NA")
   for item in item_list:
        print(item.name)
It just prints out every item in the game, instead of the item from that participant.  I also tried the Items.from_data(p.stats.items), but this throws an error.

**Comment by jjmaldonis** [comment]
Hey sorry for the delay getting back to you.

In this case there is no connection between `item_list` and `p`, so the code doesn't know that you want `item_list` to only be `p`'s items. If you want the participant items, you can do this:

```
for item in p.stats.items:
    print(item.name)
```

**Comment by aluckyhit** [comment]
All good, thanks for being patient with me.

So, I get your answer for items, but my first question still stand how do I pull the pictures for summoner spells, and keystones? It returns cassiopeia.core.staticdata.common.ImageData, and I don't see how to convert that to an actual image.

**Comment by jjmaldonis** [comment]
Oh if you want the url you use `item.image.url` and if you want the real image (for a jupyter notebook or something) you use `item.image.image`.

**Comment by aluckyhit** [comment]
Are you updating something, I cant seem to find the documentation anymore that you linked above?, and thanks!

**Comment by jjmaldonis** [comment]
Hmm I have no idea what happened. I haven't had internet for the last few nights (outside of work) so I haven't been able to keep up with this stuff. I'll try to figure out what happened when I can.
