### ISSUE TITLE
Fetching level issue

### ISSUE THREAD

**Issue by Generalarne** [meraki-analytics/cassiopeia#241]
When I'm trying to fetch my summoner level and print the value i get this: 
<merakicommons.ghost.Ghost.__property object at 0x02DB5848> 

    my code looks like this:
        name = input("Write name")
        summoner = Summoner(name=name, region="EUW")
        print(Summoner.level)

**Comment by jjmaldonis** [comment]
In your print statement, `Summoner` should be lower case ;)

**Comment by Generalarne** [comment]
I've tried that, but then i get a huge error message in return

**Comment by jjmaldonis** [comment]
If you're getting an error message, it's possible that the `name` you are passing in isn't a real summoner name for EUW or maybe your API key isn't being recognized correctly.

If you post the error message (minimally the last few lines) that would be helpful.
