### ISSUE TITLE
Long waits in Semaphore.aquire when multithreading

### ISSUE THREAD

**Issue by bmon** [meraki-analytics/cassiopeia#248]
I've got a multithreded program which is making requests across multiple regions. After spinning up one worker each for 3 different regions, I find that after about ~30 requests each, all threads will halt, waiting to acquire `_lock` on `merakicommons.ratelimits.Semaphore`. I've confirmed that I'm not hitting any app or method API ratelimits, by inspecting the headers of the most recent requests made. 

A better idea of this problem can be seen by viewing this [flame graph](https://drive.google.com/uc?id=1uTjTyNZo5y7MlDEu8B0z0YthMTcnXLi3). Thread 1,2 and 3 are the workers, and they're spending about 70% of their execution time waiting in 'Semaphore.acquire()`. Thread 4-6 are artifacts from profiling.

My issue seems similar to #183, but I'm not sure if it has the same cause. I did some logging of the calls to the Semaphore class, although I don't really understand how it's working, I did notice that `release()` does not get called very often at all.

Is there any multithreading specific setup I could be missing? I couldn't find much documentation about multithreaded setups.

Here are a couple of traces from different executions. 

[trace1.log](https://github.com/meraki-analytics/cassiopeia/files/2247998/trace1.log)
[trace2.log](https://github.com/meraki-analytics/cassiopeia/files/2247997/trace2.log)

Thanks for any help! :)

```
  File "/Users/brendanroy/.pyenv/versions/3.6.5/lib/python3.6/site-packages/cassiopeia/datastores/common.py", line 124, in get
    status_code, body, response_headers = HTTPClient._get(url, headers, rate_limiters, connection)
  File "/Users/brendanroy/.pyenv/versions/3.6.5/lib/python3.6/site-packages/cassiopeia/datastores/common.py", line 95, in _get
    limiters = [stack.enter_context(rate_limiter) for rate_limiter in rate_limiters]
  File "/Users/brendanroy/.pyenv/versions/3.6.5/lib/python3.6/site-packages/cassiopeia/datastores/common.py", line 95, in <listcomp>
    limiters = [stack.enter_context(rate_limiter) for rate_limiter in rate_limiters]
  File "/Users/brendanroy/.pyenv/versions/3.6.5/lib/python3.6/contextlib.py", line 330, in enter_context
    result = _cm_type.__enter__(cm)
  File "/Users/brendanroy/.pyenv/versions/3.6.5/lib/python3.6/site-packages/merakicommons/ratelimits.py", line 90, in __enter__
    limiter.__enter__()
  File "/Users/brendanroy/.pyenv/versions/3.6.5/lib/python3.6/site-packages/merakicommons/ratelimits.py", line 127, in __enter__
    if not self._permitter.acquire(timeout=self._timeout):
  File "/Users/brendanroy/.pyenv/versions/3.6.5/lib/python3.6/site-packages/merakicommons/ratelimits.py", line 16, in acquire
    if not self._lock.acquire(blocking=blocking, timeout=timeout):
```

**Comment by bmon** [comment]
I've done some more digging on this. I think the issue is that in `datastores.riotapi.common`, only the method rate limiters are implemented per-region, and the `"application"` rate limiter is global across all routes(:+1:) and regions(:-1:). 

Unfortunately the app and method limiters are integrated very differently and I'm not sure it will be a simple change to have app limiters per-region like the method limiters. One possible quick solution could be to change `RiotApiService._get_rate_limiter` to return both the method and app limiters, and then adjust the signature of `RiotApiService._get` to handle the parameter change. I think this would be an OK solution as `_get_rate_limiter` already receives the region as the `platform` parameter, and already does the job of initialising method limiters if they're not set already. 

I might have a stab at fixing this, but in any sort of interim the easiest fix is to run each region in a separate process.

[limiter.log](https://github.com/meraki-analytics/cassiopeia/files/2252136/limiter.log)

**Comment by m3adow** [comment]
I also observed this issue but never completely debugged it (I assumed an error in my application).

So +1 I guess.

But thanks for the analysis and especially the workaround. I'll probably implement this.

**Comment by jjmaldonis** [comment]
@bmon and/or @m3adow : This should be fixed with the latest commit, although I haven't done a ton of debugging. Can one of you check to see if the latest commit fixed the multithreading issue, or send me the code you're using that was hanging?

Thanks again for the details on this, it helped a ton.

**Comment by m3adow** [comment]
I could not replicate the error with the newest commit. Although I'm not 100% certain which version of my code I encountered it with, so take it with a grain of salt.

**Comment by jjmaldonis** [comment]
I'm going to assume that this is working now, but feel free to re-open it if not.

**Comment by bmon** [comment]
Yep, this is looking totally fixed from my end. Thanks very much!
