### ISSUE TITLE
Lazy loading too late

### ISSUE THREAD

**Issue by deekay42** [meraki-analytics/cassiopeia#249]
I'm noticing something very strange. 
I have the following fragment in my code:

 ```
...
match = cass.get_match(match_id, region="KR")
            participants = match.participants
            for participant in participants:
                champ_id = participant.champion.id
                part_id = participant.id
...
```

I'm stepping through this code with a debugger and the call
> Making call: https://kr.api.riotgames.com/lol/match/v3/matches/3312902534

is only made AFTER the first iteration of the for loop completes. I can see this in my console. The values for the initial iteration are thus all wrong, the subsequent ones are correct.

What is happening here? Why is the lazy loading executed so late?

**Comment by jjmaldonis** [comment]
That code you posted by itself works correctly. Can you paste the rest of your program?

If you are getting matches from a summoner's match history, and then using the matches' IDs later to pull the rest of the match data, then what you explained will likely happen. Why do you say that the data is wrong?

**Comment by deekay42** [comment]
I'm having trouble reproducing it now. Maybe it was due to caching or me using the api key wrong.
Essentially, when stepping through the loop with a debugger, the http call wasn't made until after the first iteration had completed. Now, however it seems that it's making it in time.  I'll let you know if I manage to reproduce again.
