### ISSUE TITLE
Champion gg help

### ISSUE THREAD

**Issue by arkcanjoo** [meraki-analytics/cassiopeia#255]
where can I find a list of commands for championgg?

**Comment by jjmaldonis** [comment]
Getting some docs for this online is still on our todo list, so for now you can take a look at the properties we define, starting ~ here: https://github.com/meraki-analytics/cassiopeia-plugins/blob/master/cassiopeia-championgg/cassiopeia_championgg/core.py#L263

You can also use python to look at the attributes you can call by printing out the results of `dir(my_object)`.

**Comment by jjmaldonis** [comment]
The docs are finally up for these types (ctrl+f: `championgg`): https://cassiopeia.readthedocs.io/en/latest/cassiopeia/champion.html

There's also an example that shows how to access the data.

:)
