### ISSUE TITLE
ValueError: 'ODYSSEY' is not a valid GameMode

### ISSUE THREAD

**Issue by alexelgier** [meraki-analytics/cassiopeia#257]
> AttributeError                            Traceback (most recent call last)
> ~/miniconda3/envs/lol/lib/python3.6/site-packages/merakicommons/cache.py in wrapper(self)
>      14         try:
> ---> 15             return getattr(self, s)
>      16         except AttributeError:
> 
> AttributeError: 'Match' object has no attribute '_lazy__mode'
> 
> During handling of the above exception, another exception occurred:
> 
> AttributeError                            Traceback (most recent call last)
> ~/miniconda3/envs/lol/lib/python3.6/site-packages/merakicommons/ghost.py in wrapper(*args, **kwargs)
>      40             try:
> ---> 41                 return method(*args, **kwargs)
>      42             except errors as error:
> 
> ~/miniconda3/envs/lol/lib/python3.6/site-packages/merakicommons/cache.py in wrapper(self)
>      16         except AttributeError:
> ---> 17             value = method(self)
>      18             setattr(self, s, value)
> 
> ~/miniconda3/envs/lol/lib/python3.6/site-packages/cassiopeia/core/match.py in mode(self)
>    1413     def mode(self) -> GameMode:
> -> 1414         return GameMode(self._data[MatchData].mode)
>    1415 
> 
> AttributeError: 'MatchData' object has no attribute 'mode'
> 
> During handling of the above exception, another exception occurred:
> 
> GhostLoadingRequiredError                 Traceback (most recent call last)
> ~/miniconda3/envs/lol/lib/python3.6/site-packages/merakicommons/ghost.py in __get__(self, obj, obj_type)
>      86             try:
> ---> 87                 return self.fget(obj)
>      88             except GhostLoadingRequiredError:
> 
> ~/miniconda3/envs/lol/lib/python3.6/site-packages/merakicommons/ghost.py in wrapper(*args, **kwargs)
>      42             except errors as error:
> ---> 43                 raise GhostLoadingRequiredError(str(error))
>      44         return wrapper
> 
> GhostLoadingRequiredError: 'MatchData' object has no attribute 'mode'
> 
> During handling of the above exception, another exception occurred:
> 
> AttributeError                            Traceback (most recent call last)
> ~/miniconda3/envs/lol/lib/python3.6/site-packages/merakicommons/cache.py in wrapper(self)
>      14         try:
> ---> 15             return getattr(self, s)
>      16         except AttributeError:
> 
> AttributeError: 'Match' object has no attribute '_lazy__mode'
> 
> During handling of the above exception, another exception occurred:
> 
> ValueError                                Traceback (most recent call last)
> <ipython-input-6-c2fbd6b94d1c> in <module>
> ----> 1 match_ids, last_timestamp = get_match_ids()
> 
> <ipython-input-5-5616fc403757> in get_match_ids(start, accounts)
>      10         matches = cass.Summoner(account=account).match_history(begin_time=start)
>      11         for match in matches:
> ---> 12             if match.mode == cass.data.GameMode.classic:
>      13                 if last_timestamp is None:
>      14                     last_timestamp = match.creation
> 
> ~/miniconda3/envs/lol/lib/python3.6/site-packages/merakicommons/ghost.py in __get__(self, obj, obj_type)
>      91                 obj._Ghost__set_loaded(load_group)
>      92 
> ---> 93                 return self.fget(obj)
>      94 
>      95     def __set_loaded(self, load_group) -> None:
> 
> ~/miniconda3/envs/lol/lib/python3.6/site-packages/merakicommons/ghost.py in wrapper(*args, **kwargs)
>      39         def wrapper(*args, **kwargs):
>      40             try:
> ---> 41                 return method(*args, **kwargs)
>      42             except errors as error:
>      43                 raise GhostLoadingRequiredError(str(error))
> 
> ~/miniconda3/envs/lol/lib/python3.6/site-packages/merakicommons/cache.py in wrapper(self)
>      15             return getattr(self, s)
>      16         except AttributeError:
> ---> 17             value = method(self)
>      18             setattr(self, s, value)
>      19             return value
> 
> ~/miniconda3/envs/lol/lib/python3.6/site-packages/cassiopeia/core/match.py in mode(self)
>    1412     @lazy
>    1413     def mode(self) -> GameMode:
> -> 1414         return GameMode(self._data[MatchData].mode)
>    1415 
>    1416     @CassiopeiaGhost.property(MatchData)
> 
> ~/miniconda3/envs/lol/lib/python3.6/enum.py in __call__(cls, value, names, module, qualname, type, start)
>     289         """
>     290         if names is None:  # simple value lookup
> --> 291             return cls.__new__(cls, value)
>     292         # otherwise, functional API: we're creating a new Enum type
>     293         return cls._create_(value, names, module=module, qualname=qualname, type=type, start=start)
> 
> ~/miniconda3/envs/lol/lib/python3.6/enum.py in __new__(cls, value)
>     531                     return member
>     532         # still not found -- try _missing_ hook
> --> 533         return cls._missing_(value)
>     534 
>     535     def _generate_next_value_(name, start, count, last_values):
> 
> ~/miniconda3/envs/lol/lib/python3.6/enum.py in _missing_(cls, value)
>     544     @classmethod
>     545     def _missing_(cls, value):
> --> 546         raise ValueError("%r is not a valid %s" % (value, cls.__name__))
>     547 
>     548     def __repr__(self):
> 
> ValueError: 'ODYSSEY' is not a valid GameMode

**Comment by jjmaldonis** [comment]
Can you try pulling the latest code from github and trying your code again? You can update using this command:

`pip install --upgrade git+https://github.com/meraki-analytics/cassiopeia.git`

**Comment by alexelgier** [comment]
it seems to work =)
thanks
