### ISSUE TITLE
How to obtain images for rune categories?

### ISSUE THREAD

**Issue by vivipiu** [meraki-analytics/cassiopeia#259]
Hey, I couldn't find a way to get the image url for rune categories like Domination, Sorcery etc. Any idea how I can get it through cassiopeia?

Thanks!

**Comment by vivipiu** [comment]
It doesn't unfortunately since I'm looking for `Domination`'s image url:
`https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/7200_Domination.png`

**Comment by jjmaldonis** [comment]
Right now we unfortunately don't have these URLs in Cass, but you can find all the filenames in the `runesReforged.json` file in datadragon.

**Comment by vivipiu** [comment]
Awe, okay. Thank you for the help!

**Comment by jjmaldonis** [comment]
Hey you can now access these images from the rune path objects using `.image_url`. For example:

```
runes = cass.Runes(region="NA")
rune = runes[0]
url = rune.path.image_url
```
