### ISSUE TITLE
incorrect position information 

### ISSUE THREAD

**Issue by HwijaeSon** [meraki-analytics/cassiopeia#276]
I have some issue in match history. When I call the match and see each participant's position, some of matches give wrong position information such as 3 junglers, top lane, mid lane. And some of mathes do not give the position informations at all. Why this happens?

**Comment by jjmaldonis** [comment]
Unfortunately that is the data that the Riot API returns. There are different methods of trying to "fix" the data to get better results. If you want to know more, I encourage you to join the Riot API discord channel and to ask there.

**Comment by tear727** [comment]
Not sure why they don't just use the role selection data from the client anyways. It makes more sense since everyone selects their own roles now. If they used that, there would still be less error than the way Riot generates it, even given the possibility that people will trade lanes.

**Comment by jjmaldonis** [comment]
Yup you're right. If you hop on the discord you can get a feel for some of the complications of getting that data into the match information. It isn't trivial.
