### ISSUE TITLE
Current Match Issues

### ISSUE THREAD

**Issue by tear727** [meraki-analytics/cassiopeia#278]
Code used
   
    name = "yassuo"
    region = "NA"
    summoner = Summoner(name=name, region=region)
    ranks_blue = [] 
    for participant in current_match.blue_team.participants:
        ranks_blue.append(participant.summoner.league_positions)

    ranks_blue = [pos.to_json() for rank in ranks_blue for pos in rank]
    for rank in ranks_blue:
        print(rank + '\n')
 
This will print out *six* different json objects instead of five (one for each blue team participant). This is the actual result I was given:

    {"name": "", "leaguePoints": 448, "division": "I", "freshBlood": false, "hotStreak": false, "position":  
    "APEX", "region": "NA", "losses": 50, "wins": 69, "summonerId": 
    "bVPks_du41X7inhpYhCNR4RRbUeJyXv-8Z2ak_7sdD7J", "veteran": false, "tier": "GRANDMASTER", 
    "summonerName": "Yassuo", "leagueId": "ce54c70c-6e6e-391b-a96e-ea9b7393e9bc", "inactive": 
    false, "queue": "RANKED_SOLO_5x5"}

    {"name": "", "leaguePoints": 359, "division": "I", "freshBlood": false, "hotStreak": false, "position": 
    "APEX", "region": "NA", "losses": 112, "wins": 136, "summonerId": 
    "8FbBka5OSuBau2A8AIe7tmQptPqXGfSFRvqHXNmw59gKTc4", "veteran": true, "tier": 
    "GRANDMASTER", "summonerName": "Ornn Support", "leagueId": "ce54c70c-6e6e-391b-a96e- 
    ea9b7393e9bc", "inactive": false, "queue": "RANKED_SOLO_5x5"}

    {"name": "Zed's Elementalists", "leaguePoints": 100, "division": "III", "freshBlood": false, "hotStreak": 
    false, "position": "NONE", "region": "NA", "losses": 5, "wins": 14, "summonerId": 
    "8FbBka5OSuBau2A8AIe7tmQptPqXGfSFRvqHXNmw59gKTc4", "veteran": false, "promos": 
    {"target":  2, "wins": 1, "progress": "WNN", "losses": 0}, "tier": "GOLD", "summonerName": "Ornn 
    Support", "leagueId": "52c7ae90-2d5c-11e9-ac1b-c81f66cf2333", "inactive": false, "queue": 
    "RANKED_FLEX_SR"}

    {"name": "", "leaguePoints": 739, "division": "I", "freshBlood": false, "hotStreak": false, "position": 
    "APEX", "region": "NA", "losses": 95, "wins": 135, "summonerId": 
    "vFvpCIFgtmAEVKPQCI6kmXqQlMXO9U4yQMhUtokQb0woKh16", "veteran": false, "tier": 
    "GRANDMASTER", "summonerName": "Yeonbee", "leagueId": "ce54c70c-6e6e-391b-a96e- 
    ea9b7393e9bc", "inactive": false, "queue": "RANKED_SOLO_5x5"}

    {"name": "", "leaguePoints": 418, "division": "I", "freshBlood": true, "hotStreak": false, "position": 
    "APEX", "region": "NA", "losses": 91, "wins": 119, "summonerId": "q1Km- 
    moL5VuwGlMTInd9ak_AWT9cVU9TR0OWejrpMs68Icg", "veteran": false, "tier": "GRANDMASTER", 
    "summonerName": "DaRkHaWk72", "leagueId": "ce54c70c-6e6e-391b-a96e-ea9b7393e9bc", 
    "inactive": false, "queue": "RANKED_SOLO_5x5"}

    {"name": "", "leaguePoints": 394, "division": "I", "freshBlood": false, "hotStreak": false, "position": 
    "APEX", "region": "NA", "losses": 119, "wins": 140, "summonerId": 
    "w7Kh3eOS2dtAlpsM1_HlP7Xzkj0zGrAnXlqlft0wRSrudGE", "veteran": true, "tier": "GRANDMASTER", 
    "summonerName": "Gabex", "leagueId": "ce54c70c-6e6e-391b-a96e-ea9b7393e9bc", "inactive": 
    false, "queue": "RANKED_SOLO_5x5"}

Notice that the second and third object both share the summoner name "Ornn Support". Yet one of them is from GOLD and one is from GRANDMASTER?

**Comment by jjmaldonis** [comment]
I believe the queues are different in those two entries.

**Comment by tear727** [comment]
@jjmaldonis I think I see the problem now. `participant.summoner.league_positions` returns all the positions for each Queue type?

**Comment by jjmaldonis** [comment]
Yes that's exactly right. I think that's the only way to do it because we don't know what queue you want.

It may be possible to do `participant.summoner.league_positions.filter(Queue.ranked_solo_fives)` -- that's certainly desirable behavior -- but I haven't tested it so I'm not sure if it works.

**Comment by tear727** [comment]
@jjmaldonis `participant.summoner.league_positions.fives` works, although I have to change a couple things after. Seems like the issue was my misunderstanding!
