### ISSUE TITLE
'LeagueEntryData' object has no attribute 'name'

### ISSUE THREAD

**Issue by artemigkh** [meraki-analytics/cassiopeia#290]
One liner to reproduce:
`for e in Summoner(name="Kalturi", region="NA").league_entries: print(e.name)`

In the debug log you can see it uses the `v4/entries/by-summoner/` endpoint, but that endpoint doesn't return the league name https://developer.riotgames.com/api-methods/#league-v4/GET_getLeagueEntriesForSummoner

**Comment by jjmaldonis** [comment]
Iirc (I haven't double checked), there are a couple endpoints that return a "LeagueEntryData" of some sort, `/v4/entries/by-summoner` being one of them. Unfortunately they don't all _exactly_ the same data.

Again, iirc, our options are to either have two nearly identical "LeagueEntryData" objects, or deal somehow with this weird use case. Maybe on an attribute error, we force a request to some other endpoint to get the name. That feels a bit like putting my finger on the scale, so I'm initially hesitant to do that. I'm not sure what the other options are though. Thoughts?

**Comment by artemigkh** [comment]
I think the cleanest way by far is to keep the one existing `LeagueEntryData` object that there is now, but just use the parent league object for data points that might not exist on the returned DTOs. For example, the original issue in this ticket can be solved with a one line fix by just changing the function to
```
    @property
    def name(self) -> str:
        return self.league.name
```
