### ISSUE TITLE
Summoner object doesn't have league_positions attribute

### ISSUE THREAD

**Issue by artemigkh** [meraki-analytics/cassiopeia#291]
It's referenced in test_examples.py -> L135 and Summoner.ranks() -> L216 but it's not defined and leads to crash 

`AttributeError: 'Summoner' object has no attribute 'league_positions'`

**Comment by jjmaldonis** [comment]
Wow, first you fix two issues and now there's two more... I don't know how to feel :)

Do you have any interest in fixing these?

For this one, the `league_positions` attribute should no longer exist because Riot got rid of them. I must have missed one in the test cases.
