### ISSUE TITLE
Any way to use multiple Riot API keys?

### ISSUE THREAD

**Issue by deekay42** [meraki-analytics/cassiopeia#295]
When downloading large sets of game data, using only one API key really bottlenecks download rate.
Is there a way to include multiple api keys to speed up downloads and circumvent the rate limit?

**Comment by jjmaldonis** [comment]
Using multiple API keys is against the Riot API's terms of service. You can ask Riot for an upgraded rate limit for your key.

But the download rate isn't that bad. You can get 1 million matches in a week with a standard dev key (not an exaggeration, I've done it many times). By the time you write you're app and test it on 100 matches, you'll have more matches than you need before applying for a production key.
