### ISSUE TITLE
Issue with matches from custom games

### ISSUE THREAD

**Issue by Bcastet** [meraki-analytics/cassiopeia#296]
Hello, I fixed an error where the lib would raise an error 403 when trying to get a match from a custom game, where link between the player and the summoner isn't established (can see it from match id 4152970687).

**Comment by jjmaldonis** [comment]
Do you remember the region for that match ID?

**Comment by Bcastet** [comment]
That was on EU

**Comment by jjmaldonis** [comment]
Ok thanks, I'll take a look when Riot releases the TFT endpoints because we'll have to change a bunch of stuff then anyways.

**Comment by Bcastet** [comment]
I already looked into it and I did that: 

class MatchData(CoreData):
    _dto_type = dto.MatchDto
    _renamed = {"gameId": "id", "gameVersion": "version", "gameMode": "mode", "gameType": "type", "queueId": "queue", "seasonId": "season"}

    def __call__(self, **kwargs):
        if "gameCreation" in kwargs:
            self.creation = arrow.get(kwargs["gameCreation"] / 1000)
        if "gameDuration" in kwargs:
            self.duration = datetime.timedelta(seconds=kwargs["gameDuration"])

        if "participants" in kwargs:
            good_participant_ids = []
            for participant in kwargs["participants"]:
                for pid in kwargs["participantIdentities"]:
                    if participant["participantId"] == pid["participantId"] and "player" in pid:
                        good_participant_ids.append(participant["participantId"])
                        participant["player"] =  pid["player"]
                        break
            # For each participant id we found that has both a participant and an identity, add it to the match data's participants
            self.participants = []
            for participant in kwargs["participants"]:
                if participant["participantId"] in good_participant_ids:
                    participant = ParticipantData(**participant)
                    self.participants.append(participant)
            print(self.participants)
            print(kwargs(["participants"]))
            assert len(self.participants) == len(kwargs["participants"])
            kwargs.pop("participants")
            kwargs.pop("participantIdentities")

        if "teams" in kwargs:
            self.teams = []
            for team in kwargs.pop("teams"):
                team_side = Side(team["teamId"])
                participants = []
                for participant in self.participants:
                    if participant.side is team_side:
                        participants.append(participant)
                self.teams.append(TeamData(**team, participants=participants))

        super().__call__(**kwargs)
        return self

it seems to work normally, the only problem being you are not certified to get participantIdentities, but since the API doesn't always provide it it seems ok for me

**Comment by jjmaldonis** [comment]
I'm pretty sure we've fixed this now. I'm going to close this.
