### ISSUE TITLE
summoner 'ranks' not working "attribute error"

### ISSUE THREAD

**Issue by Tap84** [meraki-analytics/cassiopeia#302]
When trying to retrieve summoner.ranks an attribute error is raised. For example I created a summoner object, and calling summoner.level works properly, however when I try to retrieve summoner.ranks I get the following error 

`AttributeError: 'Summoner' object has no attribute 'league_positions'`

The summoner I am testing does have a current rank.

**Comment by sgh304** [comment]
not a contributor to this project, but i believe what is happening is the riot api updated to change the general concept of `league_positions` to `league_entries`. you can see some of the changes in code [here](https://github.com/meraki-analytics/cassiopeia/commit/becf9b0e4703b40d0cf1e279eeb7777c421b7f48#diff-1a215be1e9c27aa2ab3d00c4963a889d). is it possible your installation is of an old cassiopeia version before this change was made? it looks like the [repo code](https://github.com/meraki-analytics/cassiopeia/blob/master/cassiopeia/core/summoner.py#L216) correctly uses `league_entries` for the `ranks` call

**Comment by Tap84** [comment]
How can I check my version? I ran pip install from the git repository address and my Cass is version 4.0.4

**Comment by Satrium** [comment]
Are you using any Datastore (like the Diskstore?), because i think those have not been updated yet to support the changes to the league endpoint.

**Comment by Tap84** [comment]
The fix for this was to uninstall the old version manually, then using the github link with pip correctly updated to the new code
