### ISSUE TITLE
Issue with setup (pycharm + cassiopeia)

### ISSUE THREAD

**Issue by rawora** [meraki-analytics/cassiopeia#306]
Hey,

I installed PyCharm and also Anaconda as the enviroment.
However I can't seem to get cassiopeia installed. I have tried running 'pip install cassiopeia' multiple times and its saying it is already installed.

![image](https://user-images.githubusercontent.com/12943161/68993496-ff448600-0878-11ea-9190-f5ad8711114b.png)

Where could the issue be? :/

Im thankful for any help

**Comment by jjmaldonis** [comment]
Hey my guess is that you have two versions of python installed. pip is installing Cass to one version of python, but PyCharm is using the other version of python. I usually use the command line to install packages (not pycharm) and then make sure that pycharm is using the correct version of python (or python environment).
