### ISSUE TITLE
Getting passives cooldowns

### ISSUE THREAD

**Issue by Iziman127** [meraki-analytics/cassiopeia#312]
Hello,

I am actually trying to get all spells cooldowns for each champions but I didn't find where are stored passives cooldowns in class cassiopeia.core.staticdata.champion.Passive

Can I find them somewhere else ?

Thank you

**Comment by jjmaldonis** [comment]
Hi, unfortunately Riot does not provide this data, or at least the data they do provide is very inaccurate.

**Comment by jjmaldonis** [comment]
This data is now available in json format here:
http://cdn.merakianalytics.com/riot/lol/resources/latest/en-US/champions/
