### ISSUE TITLE
Champion.load() for "Nunu ve Willump"

### ISSUE THREAD

**Issue by rasity** [meraki-analytics/cassiopeia#313]
Hi,

When I try to load data for "Nunu ve Willump" with code `Champion(name="Nunu ve Willump", region="TR")`

I got Key error for "Nunu ve Willump"

**Comment by jjmaldonis** [comment]
Hey, does it work if you set the name equal to `Nunu and Willump`? It's surprising that what you have doesn't work.

**Comment by jjmaldonis** [comment]
I'm going to close this issue, you can reopen it if it's still an issue for you.
