### ISSUE TITLE
Issue with cassiopeia developer

### ISSUE THREAD

**Issue by ahmedsafadii** [meraki-analytics/cassiopeia#320]
I just need to tell you that this amazing and effort such a perfect style for the people who want make a great world for league of legends community, I just love how you read my mind by doing all the features that I was planning to do.

Amazing one, My best love <3

**Comment by jjmaldonis** [comment]
Thank you!!! We are very happy you like it and thanks for letting us know!

**Comment by ahmedsafadii** [comment]
Thank, the issue has been resolve <3

I just want to give you feature request [Free Rotate champions and sales]

**Comment by jjmaldonis** [comment]
Haha thank you :)

I _think_ the Free to Play champions (for all and for new players) is available as a boolean property on each champion. For example, these two lines should work:

```
annie = Champion(name="Annie", region="NA")
annie.free_to_play
annie.free_to_play_new_players
```

And sales is a great idea, I think it's only available locally through the client/LCU, but I'll think on it. There may be a way to get that info.
