### ISSUE TITLE
rank_last_season inaccessible

### ISSUE THREAD

**Issue by felixchretien** [meraki-analytics/cassiopeia#326]
I am trying to access the rank_last_season attribute. Following the Sphinx documentation, it should be accessible from both the [Match participant](https://cassiopeia.readthedocs.io/en/latest/cassiopeia/match.html?highlight=match%20participant#cassiopeia.core.match.Participant) and [Summoner](https://cassiopeia.readthedocs.io/en/latest/cassiopeia/summoner.html?highlight=rank) classes, but in fact both are not.

I get an Attribute error from both

```
print(type(player))
<class 'cassiopeia.core.summoner.Summoner'>
player.rank_last_season
```

and
```
print(type(game.participants[player]))
<class 'cassiopeia.core.match.Participant'>
game.participants[player].rank_last_season
```

**Comment by jjmaldonis** [comment]
Thanks for the message. Riot removed this piece of information a while ago, so it looks like it is gone permanently. We will remove this in the next release of Cass.

**Comment by felixchretien** [comment]
Hi Jason,

Does it mean that we cannot reach any info about the players rank from the
api?

Thanks a lot,

Félix

**Comment by jjmaldonis** [comment]
That is correct.

We removed this in #429
