### ISSUE TITLE
Can't get location data of each champion

### ISSUE THREAD

**Issue by HowardHowonYu** [meraki-analytics/cassiopeia#339]
I want to make sure the lane. So that I need the location data during the whole game.
Also need to get the informations of start items.
this endpoint => "/lol/match/v4/timelines/by-match/{matchId}" 
But I don't know about the way to get the data from Cassiopeia. 
Is there any possibility to get the whole timeline data?

----
cumulative_timeline[] couldn't get some x,y positions, even I try every 10 seconds.

**Comment by paaksing** [comment]
location data are per frame, therefore per minute and in the events only a kills will give location data, because that is what the API gives, cassiopeia can't blow up new data data that API doesn't have, so every 10 second doesn't work
