### ISSUE TITLE
Trouble refreshing summoner.current_match.duration

### ISSUE THREAD

**Issue by Maulorian** [meraki-analytics/cassiopeia#342]
I need to track the duration of a match, and I see that the first time I access this field, cass makes a query to the api, but the other times it returns this first duration and that's it, is there a way to refresh or delete the cache to get an updated value?
Thank you

**Comment by paaksing** [comment]
itself the riot api will cache for 5 minute, make sure to read the cache section of the docs and adjust your expiration for `CurrentMatch`
