### ISSUE TITLE
Unclear Input to Cassiopeia.get_match

### ISSUE THREAD

**Issue by silentsilencee** [meraki-analytics/cassiopeia#353]
The documentation for Matches specifies (region: Union[cassiopeia.data.Region, str] = None as the input to the get_match function. There is another attribute not mentioned here named 'id'. What is this id and how does one find it for a given game_hash (what riot uses to index games).

**Comment by paaksing** [comment]
`id` is the game id or match id that you get from match history. The `Union[cass.data.region, str]` part means that you can give a cass region object or pass a string region, that's how union works, please review the `typing` module of python
