### ISSUE TITLE
Queue.nexus_blitz is not up to date

### ISSUE THREAD

**Issue by Schluucht** [meraki-analytics/cassiopeia#354]
Hi,

The `Queue.nexus_blitz` constant is not up to date. It should be equal to `1300`, not `1200`. `1200 `id is deprecated since patch 9.2 (ref [here](http://static.developer.riotgames.com/docs/lol/queues.json) - key 78).

It raises an error if a match in match history is a Nexus blitz type game.

Change seems straighforward. I will create an associated pull request.

Please, if I miss something, correct me.

**Comment by Schluucht** [comment]
Actually I am not allowed to push a branch with my corrections :( .

**Comment by paaksing** [comment]
You need to push the branch in your fork to create a PR

**Comment by paaksing** [comment]
And I am sure that the id of nexus blitz was fixed months ago (by Banana), something may have happened that reversed that fix.
