### ISSUE TITLE
Pull match history for entire season 10

### ISSUE THREAD

**Issue by hhase** [meraki-analytics/cassiopeia#356]
Hi!

I wanted to run `match_history(seasons={Season.season_9}, queues={Queue.ranked_solo_fives})` for season 10 and I found that this only works up to season 9. I found that in `.../cassiopeia/transformers/data.py` the `Season` class is not updated for season 10 and I wanted to ask if the needed fix would be to just update the aforementioned class.

PS: Thank you for this amazing framework! :D

**Comment by hhase** [comment]
On a similar line, when running the code line `sample_match.patch.__dict__` with a match from season 11, I get:
```
{'_region': <Region.europe_west: 'EUW'>,
 '_season': <Season.season_8: 'SEASON2018'>,
 '_name': '11.1',
 '_start': <Arrow [2021-01-06T03:00:00-02:00]>,
 '_end': None}
```

**Comment by jjmaldonis** [comment]
Yeah, you're spot on. Normally the thing to do would be to update that class, however I'm not sure Riot even updates these values any more. In their [documentation](https://developer.riotgames.com/docs/lol) (which I believe is out of date), they link to the [seasons json file](http://static.developer.riotgames.com/docs/lol/seasons.json) which only has data through season 9 in 2019.

Can you please confirm that the Riot API returns `season` values greater than `13` from the API, regardless of what the documentation says? If they do, feel free to add the corresponding seasons to the data.py file.

I'm not sure what's going on with the Patch info...

All of this said, Riot has pretty much taken the position "don't use seasons, just use timestamps instead". So at least in your own code, I would take that route instead.

**Comment by xMestas** [comment]
For the record, I queried a recent match (matchId of "NA1_3865328574") and found in the response:

. . .
"gameVersion": "11.7.366.7612",
. . . 
"seasonId": 0,
. . .

The gameVersion field indicates that this match was played during season 11, but the seasonId field is 0 (the value for preseason 3).  Seems to me that Riot is not supporting this value beyond season 10, so this feature cannot be added for seasons beyond season 9.  It may be a good idea to remove filtering by season all together?  But that's probably not a high priority fix if so.

**Comment by jjmaldonis** [comment]
We will almost certainly remove the season field when we update Cass to support Match v5, which is Riot's new format for sending match and matchlist data.
