### ISSUE TITLE
end_time doesn't seem to work for get_match_history

### ISSUE THREAD

**Issue by snwdrft** [meraki-analytics/cassiopeia#363]
```python
def test():
    summoner = Summoner(name="HULKSMASH1337", region="NA")

    #patch = Patch.from_str("11.4", region="NA")
    #start = patch.start
    #end = patch.end
    start = arrow.get(2021, 2, 18)
    end = arrow.get(2021, 2, 23)

    print(start)
    print(end)

    match_history = cass.get_match_history(summoner=summoner, begin_time=start, end_time=end)

    for match in match_history:
        print(match.participants[summoner].champion.name, match.creation)
```

Whenever I specify an end time for the get_match_history function, it ends up returning 0 but runs fine if I only mention a start time. I tried manually entering a 1-week interval as the Riot API limits it to 1-week queries, still nothing. The output call I got was https://na1.api.riotgames.com/lol/match/v4/matchlists/by-account/q2OQLfFIzcHl5nuwMLmg8hhsrY4249L2h3Roj4SSwQcaIeSf7ZJ00ui9?beginIndex=0&endIndex=100, which defers to the one I tried on developer.riotgames.com which gave me "https://na1.api.riotgames.com/lol/match/v4/matchlists/by-account/q2OQLfFIzcHl5nuwMLmg8hhsrY4249L2h3Roj4SSwQcaIeSf7ZJ00ui9?endTime=1614153600000&beginTime=1613635200000"

I'm not sure if this is an issue with Arrow, as I downgraded to version 0.17.0

**Comment by jjmaldonis** [comment]
I believe this is fixed with the Arrow version fixes. Feel free to re-open this if you're still seeing issues.
