### ISSUE TITLE
Fix Collections ABC Deprecated Import Method

### ISSUE THREAD

**Issue by LukePeltier** [meraki-analytics/cassiopeia#370]
cassiopeia/datastores/riotapi/common.py:173: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working

**Comment by LukePeltier** [comment]
Is this not going to be fixed for 3.10?

**Comment by paaksing** [comment]
> Is this not going to be fixed for 3.10?

It's a deprecation warning, just turn it off, in python people will only fix anything at the moment that it breaks which is 3.10 support and we're just at the beginning of 3.9, chill

**Comment by jjmaldonis** [comment]
Ahh, I just forgot to `push` after I fixed this. It will be updated shortly.

**Comment by LukePeltier** [comment]
> 
> 
> > Is this not going to be fixed for 3.10?
> 
> It's a deprecation warning, just turn it off, in python people will only fix anything at the moment that it breaks which is 3.10 support and we're just at the beginning of 3.9, chill

Sorry, I wasn't trying to be rude. The ticket was closed with no response.
