### ISSUE TITLE
MissingKeyError: platform must be in query!

### ISSUE THREAD

**Issue by klm4life** [meraki-analytics/cassiopeia#387]
Hi. I was trying this library out so I copied the sample code but got `MissingKeyError: platform must be in query!`

This error occurs after `challenger_league = cass.get_challenger_league(queue=cass.Queue.ranked_solo_fives)` runs. 

I am not sure about how to resolve this issue. Thanks in advance,

**Comment by eloguh** [comment]
I have the same error do you solve it?

**Comment by jjmaldonis** [comment]
You can set the region/platform like this: `challenger_league = cass.get_challenger_league(region="NA", queue=cass.Queue.ranked_solo_fives)`
