### ISSUE TITLE
Is the project active?

### ISSUE THREAD

**Issue by LuizDMM** [meraki-analytics/cassiopeia#394]

**Comment by jjmaldonis** [comment]
We haven't had much time lately to put into it, but definitely don't want Cass to be inactive. Hopefully things will lighten up in the near future and we'll have more time than we do at the moment.

**Comment by LuizDMM** [comment]
It's just a comment, but I loved the project, congratulations. I'm getting to know the code and I want to contribute.

**Comment by jjmaldonis** [comment]
Awesome happy to hear it! Contributions are always welcome.
