### ISSUE TITLE
Pypi releases not reflected with git tags on the repo

### ISSUE THREAD

**Issue by UmBsublime** [meraki-analytics/cassiopeia#395]
There is currently no new release on this repo since v4.0.5 

This doesn't really matter so to speak, but it's a bit confusing when looking at the releases on [pypi](https://pypi.org/project/cassiopeia/#history) where currently the latest release is 5.0.1

Can it be possible to add the tags also in the repo, this way I can easily determine if a bug was fixed between latest release and master.

**Comment by jjmaldonis** [comment]
If you want to take the time to go through the commit history and correlation the timestamps of the commits with the releases in pypi, and tell me which commits need which version tags, then I would be happy to tag them. I'm assuming github lets you retroactively assign releases to commits based on your comment.

**Comment by UmBsublime** [comment]
Will take a look at it this week. It should be simple as I just noticed the version has been kept up to date in setup.py, so I can probably find the appropriate commit.

Would you prefer I create a pull request with the tags, or simply list the commit IDs with related pypi version in this issue?

**Comment by jjmaldonis** [comment]
If you can create a PR that'd be great!
