### ISSUE TITLE
'MatchData' object has no attribute 'endedInEarlySurrender'

### ISSUE THREAD

**Issue by realdevvora** [meraki-analytics/cassiopeia#397]
If you run the `is_remake()` function on a match, there is no such field of `endedInEarlySurrender`.

In `cassiopeia/core/match.py/Match` on line 1777:

```
@property
    def is_remake(self) -> bool:
        return self._data[MatchData].endedInEarlySurrender or self.duration < datetime.timedelta(minutes=5)
```

I think just deleting the `self._data[MatchData].endedInEarlySurrender` would work, so it would end up as:

```
@property
    def is_remake(self) -> bool:
        return self.duration < datetime.timedelta(minutes=5)
```

**Comment by jjmaldonis** [comment]
This seems to be working again. Closing.
