### ISSUE TITLE
Including method/property return type in docs

### ISSUE THREAD

**Issue by JoshPaulie** [meraki-analytics/cassiopeia#401]
Hey all. Love Cass, use it in my discord bot.

I'm constantly checking the docs for a method (or property), then the source to see what it returns. Is there an easy way for sphinx to say (for example) `cass.Champion.blurb -> str` or `cass.get_champions() -> list[Champion]`so I could quickly navigate around the docs?

**I'd be happy to make a PR** but I'm unfamiliar with Sphinx. From the docs it looks like we might need to include a another `::symbol/decorator::` thing under each auto class. [Ref](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html). If someone could make a quick example for any of them I'd be happy to go through and add it to all the other rst pages.

**Comment by JoshPaulie** [comment]
Since Cass doesn't seem to be in a collaborative or active state, I'll be closing this issue. Thanks again for all you do ♥️

**Comment by jjmaldonis** [comment]
Hey, thanks for the message. I know we've been out of touch lately, especially me. At the time when we rewrote Cass a few years ago, I couldn't figure out a way to do what you are saying, but it would be so useful. The docs are a big pain point and require way too much maintenance. You'd think Sphinx would support what you said, so maybe there is a way that I wasn't aware of or maybe there is a way to do it today. I also don't know enough about Sphinx to know without a bunch of time googling and such. I hope we can get Cass and its docs up to date soon. Just been a lot going on with life.
