### ISSUE TITLE
matchrefdata.creation isn't present in Matchv5 calls

### ISSUE THREAD

**Issue by WeldFire** [meraki-analytics/cassiopeia#404]
The following property access will fail when trying to fetch match history. 
https://github.com/meraki-analytics/cassiopeia/blob/fb22e0dd2c71ae5e14c046379e49c8a44215e79d/cassiopeia/datastores/ghost.py#L698

line 691 - 707 isn't necessary for `cass.get_match_history()` one temporarily workaround is to disable those lines.

As for a permanent solution, checking for this field like is done on line 694 and ignoring this check if none of them are present might be a valid solution.

**Comment by jjmaldonis** [comment]
Great comment. Merged the PR to fix this, see #412
