### ISSUE TITLE
Summoner `league_entries` broken for some

### ISSUE THREAD

**Issue by WeldFire** [meraki-analytics/cassiopeia#413]
```python
cass.get_summoner(name="tlrsax54", region="NA").league_entries
```
Throws the following error:
```
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\merakicommons\ghost.py", line 41, in wrapper
    return method(*args, **kwargs)
  File "C:\Python310\lib\site-packages\cassiopeia-5.0.1-py3.10.egg\cassiopeia\core\summoner.py", line 179, in id
    return self._data[SummonerData].id
AttributeError: 'SummonerData' object has no attribute 'id'
```

Other summoners don't seem to have the same error for some reason, unsure why at the moment. Other websites can query this summoner.

**Comment by LeMixer** [comment]
For me summoner.name throws in the same way as id does in your case.

**Comment by WeldFire** [comment]
It appears that the root cause was the individual changed their name causing the Riot API to not provide any data back.  Lesson learned to use one of the other IDs instead for historical data.
This shouldn't be an issue with Cass. Closing!

**Comment by LeMixer** [comment]
I am pretty sure, I have not used the summoner name. This throws:
`summoner = summonerData.get_summoner_by_account_id(player.SummonerId)
 player.SummonerName = summoner.name` 
 It throws in the second line.
