### ISSUE TITLE
Slow rate of requests

### ISSUE THREAD

**Issue by teisseire117** [meraki-analytics/cassiopeia#416]
Hey,

I was wondering what could cause a slow rate of request ? As shown in the following .gif, there seems to be 1 request every 1 second approximatively :
![rENRf0V](https://user-images.githubusercontent.com/43145883/172755213-96e0e00d-6e1a-4b2c-8596-a2e33c57cb0a.gif)
 
As I read on another Issue ticket, the tool will not limit anything until the the limit from the API is reached, but the limit should not be reached in my case after only 1rq/s as it's stated on my Riot account that the rate should be about 500 / seconds (global) and 1600 / minutes on the endpoint (SUMMONER-V4) shown on the .gif

Thank you in advance for your help !

**Comment by paaksing** [comment]
@teisseire117 Riot API has a "Time to Respond" of > 300ms, plus cassiopeia has a decent cpu consumption on data transformation. Generally synchronous code will never be able to hit the production rate limit cap, things that helps:
- Use threads / multiprocessing.
- Use an asynchronous riot api framework (currently only Pyot is maintained).

**Comment by teisseire117** [comment]
@paaksing Would you have time to give me a basic example of how to use threads / multiprocessing ?

I know I've tried that once a long time ago, and I remember it was difficult for me to use..
If you don't have time no worries!

**Comment by teisseire117** [comment]
@paaksing Got threads working, that sped up the process by a lot, and that's only 10 maximum workers :
![CDL9ubm](https://user-images.githubusercontent.com/43145883/172823251-1920708b-54b4-4534-90e5-e0ac7e1d3776.gif)
