### ISSUE TITLE
'Match' object has no attribute '_lazy__timeline'

### ISSUE THREAD

**Issue by Davl0n** [meraki-analytics/cassiopeia#418]
HI I started experimenting a bit today and wanted to draw a kill heatmap of a random game when i ran into the following Error:
AttributeError: 'Match' object has no attribute '_lazy__timeline'
During handling of the above exception, another exception occurred:
.
.
.
WrongValueTypeError: id must be of type str in query! Got 5984912648.

My code is rather simple but I couldnt find a reason for the error.
Id appreciate a little help if anyone knows what to do so that i can draw pretty heatmaps :)

![Screenshot (68)](https://user-images.githubusercontent.com/110203766/181645950-9c35ef2a-8a64-48fa-b1a3-2774fe64e84e.png)

**Comment by jjmaldonis** [comment]
This is fixed now! See #427 and my comment in #422.

We implemented a heatmap similar to what you are talking about a long time ago and by some miracle it still works. Check out this code:

```
match = summoner.match_history[0]
match.kills_heatmap()
```
