### ISSUE TITLE
TypeError: '<' not supported between instances of 'Position' and 'Position'

### ISSUE THREAD

**Issue by JasonMendoza2008** [meraki-analytics/cassiopeia#424]
To reproduce the bug, make a virtual environment under `Python 3.10.2`. Install `cassiopeia` with `pip install cassiopeia`. And run the following script https://github.com/meraki-analytics/cassiopeia/blob/master/examples/timeline.py.

Traceback:
```
Traceback (most recent call last):
  File "C:\Users\_\Documents\Projets_Persos\League of Legends\main.py", line 43, in <module>
    print_newest_match(name="RatIRL ILY", region="EUW")
  File "C:\Users\_\Documents\Projets_Persos\League of Legends\main.py", line 33, in print_newest_match
    print("Position:", p_state.position)
  File "C:\Users\_\virtualenv\LoL\lib\site-packages\cassiopeia\core\match.py", line 871, in position
    latest_event_ts = sorted(latest_event_with_ts)[-1]
TypeError: '<' not supported between instances of 'Position' and 'Position'
```

**Comment by JasonMendoza2008** [comment]
To fix the bug, one should probably replace:
`latest_event_ts = sorted(latest_event_with_ts)[-1]
`
by:
`latest_event_ts: tuple[datetime.timedelta, Position] = sorted(latest_event_with_ts, key=lambda ts_p: ts_p[0])[-1]`

**Comment by jjmaldonis** [comment]
I'm going to say this is intentional. There isn't a valid Position that can be returned this early in the game since there is no data for it, so throwing an `IndexError` seems reasonable. Like you said, you can catch the exception if you want.
