### ISSUE TITLE
Type-hinting of Match.participants is wrong?

### ISSUE THREAD

**Issue by JasonMendoza2008** [meraki-analytics/cassiopeia#431]
In the example file: https://github.com/meraki-analytics/cassiopeia/blob/master/examples/timeline.py, we do:

```py
    summoner = Summoner(name=name, region=region)

    match_history = summoner.match_history
    match = match_history[0]
    p = match.participants[summoner]
```

`match.participants` is supposed to be a `List[Participant]` (or a `SearchableList `more precisely), but the type-checker detects an unexpected type when feeding a `Summoner` to it:
![image](https://user-images.githubusercontent.com/56092290/205459802-0346dff5-6816-4904-80da-46aa31a1709b.png)

**Comment by jjmaldonis** [comment]
Feel free to submit a PR for this.

**Comment by Kyungseo-Park** [comment]
The issue has been resolved "https://github.com/meraki-analytics/cassiopeia/pull/435". 
Can we close it?

**Comment by jjmaldonis** [comment]
Yes @Kyungseo-Park, thanks for the message.
