### ISSUE TITLE
New queue types need to be added to cassiopeia

### ISSUE THREAD

**Issue by colbyj** [meraki-analytics/cassiopeia#444]
While trying to use Cassiopeia today, I discovered that some queue types aren't represented within the Cassiopeia source code. For example, queue ID 1700 is missing.

See https://static.developer.riotgames.com/docs/lol/queues.json 
from https://developer.riotgames.com/docs/lol#working-with-lol-apis_game-constants.

**Comment by stephen19K** [comment]
I'll look into this and put up a PR!
