### ISSUE TITLE
Spectator-V4 API not available since Apr 8, 2024

### ISSUE THREAD

**Issue by misiektoja** [meraki-analytics/cassiopeia#449]
Hi,

Spectator-V4 API is not available since Apr 8, 2024.

Calling _summoner.current_match_ results in _"The Riot API returned an error on the request. The received error was 403: Forbidden"_ now.

Any plans for bringing support for Spectator-V5 API ?

**Comment by jjmaldonis** [comment]
We would love to have someone contribute and make a PR to support this!

**Comment by stephen19K** [comment]
Looks like this was fixed in https://github.com/meraki-analytics/cassiopeia/commit/6cc1a9514b24974228962c3c0d991128b3feaf0f

**Comment by misiektoja** [comment]
Yes, it indeed was. I'm closing it.
