### ISSUE TITLE
parse_match_information.py meets ValueError: 'TEAM_BUILDER_DRAFT_RANKED_5x5' is not a valid Queue

### ISSUE THREAD

**Issue by NosyFerret** [meraki-analytics/cassiopeia#54]
Hello!

First, I'd like to apologize in advance for my scrubliness. I'm very new to Python and this whole API thing in general. I literally just updated Python to 3.X, pip installed cassiopeia, copied some test code, and ran it. The first test code (with the "{name} is a level {level} summoner on the NA server" stuff) worked just fine. But then I tried the one for Dyrus' information and I get the following output:

Basic match information:
  Match ID: 2100218822
  Version/Patch: 6.3.0.240
  Creation date: 2016-02-17 19:07:55.464000  (which was -1 day, 19:29:12.675141 ago)
  Duration: 0:32:24
  Map: Map.summoners_rift
  Mode: GameMode.classic
  Type: GameType.matched
  Platform: Platform.north_america
Traceback (most recent call last):
  File "parse_match_information.py", line 88, in <module>
    main()
  File "parse_match_information.py", line 32, in main
    print("  Queue: {0}".format(match.queue))
  File "//anaconda/lib/python3.5/site-packages/cassiopeia/type/core/match.py", line 91, in queue
    return cassiopeia.type.core.common.Queue(self.data.queueType) if self.data.queueType else None
  File "//anaconda/lib/python3.5/enum.py", line 235, in __call__
    return cls.__new__(cls, value)
  File "//anaconda/lib/python3.5/enum.py", line 470, in __new__
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 'TEAM_BUILDER_DRAFT_RANKED_5x5' is not a valid Queue

Is this an error associated with how Riot has been updating the queue interfaces, or did I do something wrong?

Sorry I'm such a scrub! D:
And thank you in advance for your help!

**Comment by robrua** [comment]
Hey - you're running into this because the version of Cass you're using (probably 0.1.0 if you just pip installed it) doesn't contain [this commit](https://github.com/meraki-analytics/cassiopeia/commit/a3b6d2f7231796fa4931ff94e2c37a0f06dfcf47). This is mostly my bad, as I've been a little slow on pushing new releases out.

I'll get a new release out tonight if I can, and hopefully after that you should be able to re-install and get working.

Alternatively, if you want to stay up-to-date on the very newest updates when a release hasn't been put out yet, I'd recommend cloning the git repo directly and adding it your PYTHONPATH environment variable.

**Comment by jjmaldonis** [comment]
Also if you have never had to add anything to your PYTHONPATH, then the little bit of extra information in the Setup section here might help:  https://github.com/meraki-analytics/buildcalculator

**Comment by robrua** [comment]
Just made the newest release.

**Comment by NosyFerret** [comment]
@robrua Ah! Thank you so much! I really appreciate the help! I'll probably be back with more questions at some point.

@jjmaldonis Since I'm really new to Python, what does adding things to my PYTHONPATH do?

**Comment by jjmaldonis** [comment]
Your PYTHONPATH is a system environment variable that keeps track of the location of all the python packages you have on your system. There is a default location that all python packages are "installed" depending on whether you are on windows/mac/linux. When a python package is "installed" (e.g. via pip), usually all it means is that the code gets put into that default location. Then when you `import package_name`, python looks in the default location for a package with name `package_name`, which it then imports. If python does not find the package in the default location, it will continue looking in any other directories you specify within your PYTHONPATH system environment variable (which, by the way, gets loaded into `sys.path` within python so you can see it there too).

So when you add e.g. `C:/Users/MyUsername/cassiopeia` to your PYTHONPATH and `import cassiopeia`, python will look inside that folder for something to import called `cassiopeia`, which it will find and then successfully import for you to use.

Hopefully that made sense?

**Comment by NosyFerret** [comment]
That makes perfect sense! Thank you for being so helpful! :)
