### ISSUE TITLE
'UNRANKED' Tier handling

### ISSUE THREAD

**Issue by simoncos** [meraki-analytics/cassiopeia#55]
```
  File "...\cassiopeia\type\core\match.py", line 178, in previous_season_tier
    return cassiopeia.type.core.common.Tier(self.data.participant.highestAchievedSeasonTier) if self.data.participant.highestAchievedSeasonTier else None

  File "C:\Anaconda3\lib\enum.py", line 235, in __call__
    return cls.__new__(cls, value)

  File "C:\Anaconda3\lib\enum.py", line 470, in __new__
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))

ValueError: 'UNRANKED' is not a valid Tier
```

Here if `self.data.participant.highestAchievedSeasonTier` has a value `'UNRANKED'`, it will raise a `ValueError`.

The `Tier ` class in `cassiopeia.type.core.common` does not have one unranked value:

```
class Tier(enum.Enum):
    challenger = "CHALLENGER"
    master = "MASTER"
    diamond = "DIAMOND"
    platinum = "PLATINUM"
    gold = "GOLD"
    silver = "SILVER"
    bronze = "BRONZE"
```
After I add a line it's okay:     

`unranked = "UNRANKED" `

I'm not quite familiar with the manner of Github and do not know if it's appropriate to commit a fix like this.

**Comment by jjmaldonis** [comment]
Thanks @simoncos, this should be fixed now. If you'd like to know how to commit a fix like this yourself in the future, the way to do that is to submit a pull request after forking Cassiopeia into your own repository list. You can then make changes and create a pull request, and any further modifications to those file(s) will be able to be seen within the pull request on Cass' main repo. I found this website to be helpful: https://yangsu.github.io/pull-request-tutorial/

**Comment by simoncos** [comment]
Thanks @jjmaldonis !

**Comment by sbrodehl** [comment]
With the new file upload it should be possible to create a PR via uploading the file with the fixed content. Did not test that tho :-/
