### ISSUE TITLE
AttributeError: 'MatchReference' object has no attribute 'platformid'

### ISSUE THREAD

**Issue by simoncos** [meraki-analytics/cassiopeia#58]
Here is the problem:

`match_reference_list ` was obtained by

`match_reference_list = riotapi.get_match_list(summoner=summoner, seasons=seasons, ranked_queues=ranked_queues)`

Then I wanted `match_reference_list[0].platform` and got:

```
Traceback (most recent call last):

  File "<ipython-input-2-cd23f710ee43>", line 1, in <module>
    match_reference_list[0].platform

  File "C:\Anaconda3\lib\site-packages\cassiopeia\type\core\matchlist.py", line 55, in platform
    return cassiopeia.type.core.common.Platform(self.data.platformid) if self.data.platformid else None

AttributeError: 'MatchReference' object has no attribute 'platformid
```

However, `match_reference_list[0].data` returned:

`MatchReference({'platformId': 'NA1', 'role': 'SOLO', 'lane': 'TOP', 'queue': 'RANKED_SOLO_5x5', 'matchId': 2067797383, 'season': 'PRESEASON2016', 'champion': 92, 'timestamp': 1452811832918})`

and `cassiopeia.type.core.matchlist.MatchReference.platform` returned: `<property at 0x13bbcdae188>`

**Comment by MarcusMann** [comment]
I have the same problem

**Comment by jjmaldonis** [comment]
So this issue was from an older version of the code that has since been completely rewritten. You should be able to update Cass via pip to get the newest version.
