### ISSUE TITLE
ban.champion.name for ban in match.red_team.bans Returns nothing

### ISSUE THREAD

**Issue by NosyFerret** [meraki-analytics/cassiopeia#59]
Hello!

Thank you so much for your help last time, I thought it was very useful! I'm running into another problem again. The line
    print("  Red Team Bans: {0}".format([ban.champion.name for ban in match.red_team.bans]))
Returns
  Red Team Bans: []
Which I know is incorrect, because this game is a ranked 5v5. Do you know what I'm messing up on? This line was taken from the file parse_match_information.py

Thank you so much in advance!

**Comment by WxWatch** [comment]
There has been an ongoing issue with the Riot API where bans weren't being populated. If that's the case, then we're at the mercy of Riot until they get this fixed.

**Comment by NosyFerret** [comment]
> There has been an ongoing issue with the Riot API where bans weren't being populated. If that's the case, then we're at the mercy of Riot until they get this fixed.

Nuuuuuuuuuu
