### ISSUE TITLE
calculate_average_kda example issues

### ISSUE THREAD

**Issue by methodds** [meraki-analytics/cassiopeia#62]
Hi,

I think in your example script line 41 ``deaths += participant.stats.kills`` needs to be adjusted to ``deaths += participant.stats.deaths``.

In addition, for me 
``stats = stats[StatSummaryType.ranked_fives].stats
    print("Total ranked K/D/A for {0}:  {1}/{2}/{3} == {4}".format(dyrus.name, stats.kills, stats.deaths, stats.assists, round(stats.kda, 3)))
``

throws an ``AttributeError: 'NoneType' object has no attribute 'kills'``

**Comment by jjmaldonis** [comment]
Fixed the typo.

@robrua, if a call fails in [`exectue_request`](https://github.com/meraki-analytics/cassiopeia/blob/master/cassiopeia/dto/requests.py#L106) then `None` gets returned right? What does "fail" mean in this case? Should this instead raise an exception?

**Comment by robrua** [comment]
In this case `stats[StatSummaryType.ranked_fives].stats` is returning `None`, so querying it for kills is impossible.

This is the intended behavior - we shouldn't be creating an `AggregatedStats` object if Riot doesn't send one, and if we started raising exceptions whenever one piece of data is missing you couldn't ever finish a call without an exception.

I think we should just change the example to `StatSummaryType.normal_fives` for now, as that doesn't cause the same problem and should be more robust to season/name changes that might break the example
