### ISSUE TITLE
AttributeError: 'datetime.timedelta' object has no attribute 'time

### ISSUE THREAD

**Issue by methodds** [meraki-analytics/cassiopeia#63]
calling time on frame.timestamp throw an AttributeError:

```
for frame in match.timeline.frames:
    print("The following skill level up events occured between minute {} and {}".format(frame.timestamp.time.minute, 
                                frame.timestamp.time.minute + match.timeline.frame_interval))


---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-95-6aa68e02efc5> in <module>()
      1 from cassiopeia.type.core.common import EventType
      2 for frame in match.timeline.frames:
----> 3     print("The following skill level up events occured between minute {} and {}".format(frame.timestamp.time.minute, 
      4                                 frame.timestamp.time.minute + match.timeline.frame_interval))
      5     for event in frame:

AttributeError: 'datetime.timedelta' object has no attribute 'time'
```

On a sidenote, your links  for the examples in the documentation are broken, I think there is an *s* missing after *example*:

https://github.com/meraki-analytics/cassiopeia/blob/master/example/is_dyrus_in_game.py

**Comment by jjmaldonis** [comment]
There is still an issue with this code block.

**Comment by methodds** [comment]
Could this be because skill_level_ups are not noticed as events anymore? For my example match I tried the following:

```
events = []
for frame in match.timeline.frames:
    for event in frame:
        events.append(event.type)

set(events)

Out[149]:
{<EventType.kill: 'CHAMPION_KILL'>,
 <EventType.building_kill: 'BUILDING_KILL'>,
 <EventType.item_purchase: 'ITEM_PURCHASED'>,
 <EventType.elite_monster_kill: 'ELITE_MONSTER_KILL'>,
 <EventType.ward_kill: 'WARD_KILL'>,
 <EventType.item_sale: 'ITEM_SOLD'>,
 <EventType.item_destruction: 'ITEM_DESTROYED'>,
 <EventType.ward_placement: 'WARD_PLACED'>}
```
This is why ``if event.type == EventType.skill_level_up:`` throws an ``AttributeError``

**Comment by methodds** [comment]
Thank you for the fix. Do you have an idea why skill_level_ups are not returned by the API as an event? The above example is from a 40min dynamic queue match (which therefore should include quite a number of level ups). Sorry for hijacking this issue, but I did not want to bombard you with 234082340 several issues within one hour ;-)

**Comment by jjmaldonis** [comment]
Haha no worries. I have no idea why skill_level_ups are not returned anymore. If you test a couple other matches and the same thing is happening, I think it's worth a forum post.
