### ISSUE TITLE
AttributeError: 'Image' object has no attribute 'full'

### ISSUE THREAD

**Issue by methodds** [meraki-analytics/cassiopeia#64]
In your [documentation](http://cassiopeia.readthedocs.org/en/latest/vs.html?highlight=image) for *riot API vs base API* you list a method ``full`` for images. Calling this method raises an exception:

```

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-122-658f312182ae> in <module>()
----> 1 match.participants['methodds'].champion.image.full

AttributeError: 'Image' object has no attribute 'full'
```
In addition, while calling ``image.link`` returns a string, e.g. ``Karma.png``, what would be the base url for this image? I would like to use cassiopeia for downloading all champion images.

**Comment by robrua** [comment]
You can find information on how to get the full URL at https://developer.riotgames.com/docs/static-data.

Currently Cass doesn't fill the entire URL in automatically, as many URLs require a data dragon version; we would need a call to the Versions endpoint, which currently isn't cached. We're playing with options on the next major version to make this happen though

**Comment by methodds** [comment]
Ah okay thanks for the info So basically you need to check for the first result in https://ddragon.leagueoflegends.com/api/versions.json?

And the entire URL would then be http://ddragon.leagueoflegends.com/cdn/ + first result + /img/champion/Karma.png:

http://ddragon.leagueoflegends.com/cdn/6.6.1/img/champion/Karma.png

**Comment by robrua** [comment]
That's the process. You can also get the latest version using `riotapi.get_versions ()[0]`
