### ISSUE TITLE
SQLAlchemyDB using SQLite

### ISSUE THREAD

**Issue by blackpan2** [meraki-analytics/cassiopeia#66]
To use a local sqlite database, the form would be as follows (excerpt [pull_masters_tier.py](https://github.com/meraki-analytics/cassiopeia/blob/master/examples/pull_masters_tier.py#L32)): 

**32** `db = SQLAlchemyDB("sqlite", "", "", "", "/database.db")' 
In order to get: sqlite:///database.db

However this throws **sqlalchemy.exc.ArgumentError** even though the [engine creation documentation](http://docs.sqlalchemy.org/en/latest/core/engines.html#sqlite) says that this would be an acceptable form. 

Resolved by amending [store.py](https://github.com/meraki-analytics/cassiopeia/blob/ebfca7ec961f8966f754ffca9f3e2943b5e108dc/cassiopeia/type/api/store.py#L238):

**238** 

```
try:
    self.db = sqlalchemy.create_engine("{flavor}://{username} {password}@{host}/{database}".format(flavor=flavor, host=host, database=database, username=username, password=password))
except sqlalchemy.exc.ArgumentError:
    self.db = sqlalchemy.create_engine("{flavor}:///{database}".format(flavor=flavor, database=database))
```

**Comment by jjmaldonis** [comment]
How easy is it to turn this into an if statement? I'm not 100% sure about this, but I feel like if I misspell "password" to "pasword" or something, SQLAlchemy will return an ArgumentError and then try to create the 2nd database without a password.

Also, if there was a typo in my spelling of "flavor" and I was also using a password, this would try to create the password-less version of the SQL engine. It would still error, but the foremost error would be a password-less call to create engine, which would probably confuse me for a minute until I scrolled up to look at the full traceback.

I hope that we may be able to use an if statement to identify what which version the user wants, and that that implementation will be more fault-tolerant. Opinions?

**Comment by blackpan2** [comment]
Unfortunately I'm not sure I initially looked at using if the parameters are blank do this (else proceed normally), but it was throwing the error still. I totally agree and when I get another chance to look at this I will let you know

**Comment by kihashi** [comment]
Would it be easier to just detect if the flavor was `sqlite` and use a different `create_engine` statement?

```python
if flavor == 'sqlite':
    self.db = sqlalchemy.create_engine("{flavor}:///{database}".format(...))
else:
    self.db = ...
```

As far as I know, sqlite is the only exception for [SQLAlchemy's create_engine syntax](http://docs.sqlalchemy.org/en/latest/core/engines.html#sqlite).

You could also omit the `/` before the database to allow an in-memory sqlite db, but that comes at the cost of making the way db name's are specified inconsistent since you would need to have `/db_name.sqlite` for relative files and `//path/to/db.sqlite` for absolute paths.

**Comment by jjmaldonis** [comment]
That sounds reasonable to me.  If you can create the logic and make a pull request with it implemented in Cass, I'd be happy to merge it.

Make sure to test it though!

**Comment by kihashi** [comment]
Awesome. I'd be happy to. Cheers!
