### ISSUE TITLE
'Stats' object is not callable

### ISSUE THREAD

**Issue by MonsterCWP** [meraki-analytics/cassiopeia#72]
Hey,
         I'm having an issue with getting games[0].stats to work. I'm trying to get information from the game, but when I add anything to the end of it, even if it says that it should work, I just get an error.

Example Code:
`from cassiopeia import riotapi
riotapi.set_region("NA")
riotapi.set_api_key("#My API key is here#")

summoner = riotapi.get_summoner_by_name("MonsterCWP")
games = riotapi.get_recent_games(summoner)
gamewin = games[0].stats(summoner).win
print(gamewin)`

Error when run:
Traceback (most recent call last):
   File "Test.py", line 8, in <module>
      gamewin = games[0].stats(summoner).win
TypeError: 'Stats' object is not callable

Also, not sure if this is relevant, but 
print(games.stats) 
just prints "Stats" in the console and nothing else. Not sure if that is intended.

Anything incredibly obvious that I'm doing wrong, or is it something else?
Thanks.

**Comment by jjmaldonis** [comment]
Hey, whenever you get a `not callable` error, it means you have parentheses after a variable that is not a function. In this case, `stats` in `games[0].stats` has parentheses after it, but `stats` is an class instance -- not a function -- and it can't be called.

I think

    gamewin = games[0].stats.win

is what you want?

In your code, the variable `games` is already inherently about the summoner you used to get those games in the line `games = riotapi.get_recent_games(summoner)`, so the next line already knows that `games` is about `summoner`, and you don't need to put it in parentheses again. Hopefully that made sense...

**Comment by MonsterCWP** [comment]
Alright, that worked. Thanks.
