### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by sjTaylor** [meraki-analytics/cassiopeia#76]
Not really sure if it should go here, but the documentation for cassiopeia.riotapi, cassiopeia.baseriotapi, and cassiopeia.type.core at the [documentation site](http://cassiopeia.readthedocs.io/en/latest/index.html) are currently blank. 
Yesterday they were not.

edit: something else odd is that if I [search for something](http://cassiopeia.readthedocs.io/en/latest/search.html?q=get_summoner_names&check_keywords=yes&area=default) the search succeeds, but still leads to a blank doc page.

**Comment by jjmaldonis** [comment]
Hey thank you for the report, this is definitely the right spot for it. I missed a comma so python wouldn't load cass properly, and the documentation engine therefore wasn't able to read the files. It should be good now. Please reopen the issue if things are still not working.
