### ISSUE TITLE
Cache problems with requests on different regions

### ISSUE THREAD

**Issue by hawk93** [meraki-analytics/cassiopeia#80]
I found a problem calling get_summoner_by_name methods on riotapi.
If I search for a summoner with the same name in 2 different regions I get 2 times the same summoner cause of caching that doesn't check for region match
simple test:
`riotapi.set_region('EUW')`
`summ1=riotapi.get_summoner_by_name('INC Hawkido')`
`riotapi.set_region('EUNE')`
`summ2=riotapi.get_summoner_by_name('INC Hawkido')`
`print(summ1.to_json())`
`print(summ2.to_json())`
Both summoners are equal but "INC Hawkido" doesn't exist in EUNE

**Comment by jjmaldonis** [comment]
Thanks for both the report and posting the example. We will figure out how to fix this.

**Comment by hawk93** [comment]
A possible solution is to add region to summoner record and use the tuples (region, name) and (region, id) as keys of the table instead of name and id as you do now

**Comment by robrua** [comment]
Hey, unfortunately you're right that the caching doesn't currently support multiple regions (nor does the rate limiting). We're going to redesign Cass sometime in the next few weeks/months to better support a lot of things we're missing right now, multiple regions included. The "band-aid" fix that exists for this right now would probably be to either disable caching entirely or to reset your cache every time you switch regions.

**Comment by jjmaldonis** [comment]
Closing old issues because many things have changed with the Cass rewrite.
