### ISSUE TITLE
begin_end

### ISSUE THREAD

**Issue by MarcusMann** [meraki-analytics/cassiopeia#83]
It would be a good practice to add the begin_end in the match_list function

:)

**Comment by robrua** [comment]
Are you talking about the beginIndex and endIndex parameters from https://developer.riotgames.com/api/methods#!/1213/4697?

We currently handle those using the begin_index and num_matches parameters in get_match_list (https://github.com/meraki-analytics/cassiopeia/blob/master/cassiopeia/core/matchlistapi.py#L10).

**Comment by MarcusMann** [comment]
Thanks 👍
