### ISSUE TITLE
Issue with get_matches and sqlalchemy store

### ISSUE THREAD

**Issue by fculpo** [meraki-analytics/cassiopeia#89]
I have a recurrent issue with riotapi.getmatches when using SQLAlchemy store (when trying to insert result in the db as i can tell) :

```python
summoner = riotapi.get_summoner_by_name("somesummoner")
match_list = riotapi.get_match_list(summoner, num_matches=5)
matches = riotapi.get_matches(match_list,include_timeline=False)
```

Always return this type of exception:

`sqlalchemy.exc.DataError: (psycopg2.DataError) integer out of range [SQL: 'INSERT INTO "MatchTeam" ("baronKills", "dominionVictoryScore", "dragonKills", "firstBaron", "firstBlood", "firstDragon", "firstInhibitor", "firstTower", "inhibitorKills", "teamId", "towerKills", "vilemawKills", winner, _match_id) VALUES (%(baronKills)s, %(dominionVictoryScore)s, %(dragonKills)s, %(firstBaron)s, %(firstBlood)s, %(firstDragon)s, %(firstInhibitor)s, %(firstTower)s, %(inhibitorKills)s, %(teamId)s, %(towerKills)s, %(vilemawKills)s, %(winner)s, %(_match_id)s) RETURNING "MatchTeam"._id'] [parameters: {'firstInhibitor': True, 'dominionVictoryScore': 0, 'towerKills': 11, 'vilemawKills': 0, 'firstBlood': False, 'inhibitorKills': 4, 'baronKills': 0, 'firstDragon': True, 'winner': True, 'dragonKills': 2, 'teamId': 100, '_match_id': 2981258786, 'firstBaron': False, 'firstTower': True}]`

Can you reproduce it ?
Could it be related to psycopg2 (i am not familiar with it).

Thx

**Comment by jjmaldonis** [comment]
Try changing `Integer` on this line to a `BigInteger` -- let us know if that fixes it too please.

https://github.com/meraki-analytics/cassiopeia/blob/master/cassiopeia/type/dto/match.py#L665

**Comment by fculpo** [comment]
Seems indeed that Match IDs keys need BigInteger columns (as defined athttps://github.com/meraki-analytics/cassiopeia/blob/master/cassiopeia/type/dto/match.py#L598)
I had to change all lines with `_match_id` to BigInteger:
https://github.com/meraki-analytics/cassiopeia/blob/master/cassiopeia/type/dto/match.py#L629
https://github.com/meraki-analytics/cassiopeia/blob/master/cassiopeia/type/dto/match.py#L641
https://github.com/meraki-analytics/cassiopeia/blob/master/cassiopeia/type/dto/match.py#L665

**Comment by fculpo** [comment]
submitted #90

**Comment by fculpo** [comment]
PR #93 submitted
