### ISSUE TITLE
None Type returned when accessing Summoner Object/id from Participant List

### ISSUE THREAD

**Issue by LeviMatus** [meraki-analytics/cassiopeia#91]
When attempting to get a list of summoner objects from the participants of a match from the riotapi class, all Summoner information is returned as a None Type. 
```python
    # argv takes in a command line arg which is a summoner's id
    def main(argv):

    # api information here

        summoner = riotapi.get_summoner_by_id(argv[1])         # get summoner in question
        matches = riotapi.get_recent_games(summoner)           # get that summoner's recent matches
        for match in matches:
                currMatch = riotapi.get_match(match.id)                 
                participants = currMatch.participants                      
                for participant in participants:
                        print(participant.champion)             # prints champion as expected
                        print(participant.id)                   # throws none type error
                        print(participant.summoner)             # throws none type error
```
as you can see from above, this snippet will print out champion information of a participant from a specified match as expected. However, when attempting to get summoner information, None is returned instead of the expected types and values.

Perhaps I am missing something or doing something wrong. If so, please let me know. Either way I thought best to bring this to y'alls attention.

**Comment by jjmaldonis** [comment]
Thanks for the report. Your code works for me using the summoner ID `21359666`. It's possible that the entire summoner endpoint was down for some reason when you were trying.

What summoner ID were you using? What happens if you try `21359666`?

**Comment by mant1c0r3** [comment]
It also seems to be working for me now as well. I'm using id 31073263. A few Summoner objects still come up as none. 

Using the id you provided works 100% as expected.

**Comment by jjmaldonis** [comment]
Closing old issues because many things have changed with the Cass rewrite.
