### ISSUE TITLE
Lethality Runes

### ISSUE THREAD

**Issue by y03s** [meraki-analytics/cassiopeia#95]
Riot Games didn't add stats to the Lethality Runes.
Because of this, the Libary always crashed when you execute "getRunes()". 
[Here](https://developer.riotgames.com/discussion/community-discussion/show/TFvNl8zK) is the developer.riotgames thread to this problem. 
Can you please let cassiopeia simply ignore the stats when they doesnt exists?

**Comment by y03s** [comment]
My solution:
in **cassiopeia.type.dto.staticdata.py**
line **921** and line **922** to: 
`val = dictionary.get("stats", None)`
 `	ifval != {}: `                          
`            self.stats = BasicDataStats(val) if val and not isinstance(val, BasicDataStats) else val`

**Comment by jjmaldonis** [comment]
Hey, I'm not able to reproduce the error.  Can you post the code that is giving you the error along with the error message?

**Comment by y03s** [comment]
Here is a demo code
[demo.txt](https://github.com/meraki-analytics/cassiopeia/files/790133/demo.txt)
You need to add a database to get the bug "working".
The Problem is Riot Games did not add the Stats Property to the new Runes, so the insert into the Database failes.
Cant reproduce the Error cause  i fixed it locally with the code above.
My Fix simply checks if Stats are not set and then skip the insert of the stats.

**Comment by jjmaldonis** [comment]
Ok thanks for explaining why this occurred, we will apply your fix.
